"""Machine-readable API specification for AI agents."""

from syte import __version__
from syte.design_contract import build_design_contract_spec, build_system_prompt


def build_ai_spec(base_url: str = "") -> dict:
    base = base_url.rstrip("/")
    auth = {
        "type": "api_key",
        "header": "X-API-Key",
        "alternative": "Authorization: Bearer <token>",
        "token_prefix": "syte_",
        "create_token": "POST /api/tokens with {\"name\": \"my-agent\"} — no auth required (GUI/local). Token shown once.",
        "example_header": "X-API-Key: syte_xxxxxxxxxxxxxxxx",
    }
    design = build_design_contract_spec()
    return {
        "name": "Syte Deployment API",
        "version": __version__,
        "description": "Deploy Next.js websites on a Linux server. Follow design_contract for all UI generation. Deploy via issue_deploy only.",
        "base_url": f"{base}/api" if base else "/api",
        "documentation": f"{base}/api/" if base else "/api/",
        "authentication": auth,
        "system_prompt": build_system_prompt(),
        "design_contract": design,
        "deploy_rules": design["deploy_rules"],
        "errors": {
            "401_missing_api_key": "Send X-API-Key or Authorization: Bearer header",
            "401_invalid_api_key": "Token revoked or incorrect",
            "400_invalid_path": "File path escapes workspace sandbox",
            "400_create_failed": "Duplicate UUID or validation error",
            "400_build_forbidden": "npm run build blocked — use POST /api/issue_deploy instead",
            "404_not_found": "Project UUID does not exist",
        },
        "workflow_create_website_from_git": [
            "1. POST /api/tokens → save token",
            "2. POST /api/create_project {name, git_url, branch} → uuid (do NOT set deploy:true)",
            "3. POST /api/issue_deploy {uuid} → git pull + docker build + start",
            "4. GET /api/projects/{uuid}/logs/stream?live=1 (SSE) → watch deploy",
            "5. GET /api/workspace_get?uuid= → confirm url, ssl.active, and running=true",
            "6. POST /api/validate_design?uuid= → design contract linter",
            "7. POST /api/set_domain {uuid, domain} → optional custom HTTPS domain (auto-assigned on deploy if omitted)",
        ],
        "workflow_create_website_from_scratch": [
            "1. Read system_prompt + design_contract — follow Sycord Design Contract",
            "2. POST /api/create_project {name} only → uuid + execute_command.body",
            "3. POST /api/write_file — scaffold Next.js + shadcn/ui + Tailwind per design_contract",
            "4. POST /api/execute_command — npm install, npm run lint (testing ONLY, never npm run build)",
            "5. POST /api/start_preview {uuid} → live HMR preview in seconds (preview_url)",
            "6. POST /api/write_file — iterate; preview hot-reloads automatically",
            "7. POST /api/validate_design?uuid= → check design contract",
            "8. POST /api/issue_deploy {uuid} → production docker build + start",
            "9. POST /api/stop_preview {uuid} → stop dev server when done",
        ],
        "workflow_live_preview": [
            "1. Set preview_base_domain (e.g. sycord.site) + Cloudflare token in Settings; wildcard DNS *.sycord.site → server",
            "2. POST /api/start_preview {uuid} → preview_url e.g. https://previewk-mysite.sycord.site",
            "3. GET /api/preview_status?uuid= → poll until preview_ready=true; check ssl.preview.active",
            "4. Open preview_url — HMR live; POST /api/write_file edits hot-reload",
            "5. GET /api/projects/{uuid}/preview/logs/stream?live=1 → dev server logs",
            "6. POST /api/stop_preview {uuid} when finished",
        ],
        "preview_api": {
            "description": "Fast live preview via next dev/vite — HTTPS on wildcard GUI zone",
            "domain_format": "preview{random_letter}-{appname}.sycord.site (e.g. previewk-mysite.sycord.site)",
            "domain_rules": {
                "pattern": "preview{a-z}-{appname-slug}.{gui-zone}",
                "example": "https://previewk-mysite.sycord.site",
                "ssl": "Automatic via wildcard *.sycord.site — no per-preview DNS",
                "vite_allowed_hosts": "Auto: patches vite.config.* with server.allowedHosts: true on start_preview",
                "nextjs_origins": "Auto: allowedDevOrigins patched in next.config on start_preview",
                "iframe_embed": "frame-ancestors * — preview embeddable in iframes on sycord.com or any website",
                "preview_base_domain": "Settings preview_base_domain — separate wildcard zone for preview URLs (default: GUI zone)",
                "preview_host_pattern": "preview{a-z}-{appname}.{preview_zone}",
                "not_used": "No preview.app.example.com third-level subdomains",
                "no_gui_domain": "preview_url = preview_direct_url (http://IP:4000+)",
            },
            "endpoints": {
                "start": "POST /api/start_preview {\"uuid\":\"...\"}",
                "status": "GET /api/preview_status?uuid=...",
                "stop": "POST /api/stop_preview {\"uuid\":\"...\"}",
                "logs": "GET /api/projects/{uuid}/preview/logs/stream?live=1",
            },
            "response_fields": [
                "preview_url", "preview_domain", "preview_domain_url",
                "preview_direct_url", "preview_ready", "preview_running",
                "preview_port", "preview_stream_url", "preview_dns_hint",
                "ssl.preview", "ssl.badge", "ssl.badge_label",
                "iframe.all_ok", "iframe.items", "iframe.frame_csp",
            ],
            "iframe_debug": "GET /api/projects/{uuid}/preview/iframe-check",
        },
        "production_ssl": {
            "description": "Production HTTPS via wildcard zone or per-host Caddy auto-HTTPS",
            "domain_format": "{app-slug}.{zone} (e.g. mysite.sycord.site) — auto-assigned on issue_deploy when no domain set",
            "domain_rules": {
                "auto_assign": "On successful deploy, Syte assigns {slug}.{preview_zone} when projects.domain is empty",
                "custom": "POST /api/set_domain overrides auto-assigned hostname",
                "ssl": "Automatic via wildcard *.{zone} when Cloudflare token configured",
                "no_zone": "url = http://{public_ip}:{port} until preview zone is configured",
            },
            "response_fields": [
                "url", "domain", "domain_url", "ssl.production", "ssl.badge", "ssl.badge_label",
            ],
        },
        "endpoints": [
            {"method": "GET", "path": "/api/server_info", "auth": True, "description": "Server IP, version, URLs"},
            {"method": "GET", "path": "/api/ai.json", "auth": False, "description": "This spec + design_contract + system_prompt"},
            {"method": "GET", "path": "/api/validate_design?uuid=", "auth": True, "description": "Run design contract linter on project"},
            {"method": "GET", "path": "/api/workspace_list", "auth": True, "description": "List all projects"},
            {"method": "GET", "path": "/api/workspace_get?uuid=", "auth": True, "description": "Single project details + URLs"},
            {"method": "GET", "path": "/api/list_files?uuid=&path=", "auth": True, "description": "List files in workspace"},
            {"method": "POST", "path": "/api/read_file", "auth": True, "body": {"uuid": "str", "path": "str"}},
            {"method": "POST", "path": "/api/write_file", "auth": True, "body": {"uuid": "str", "path": "str", "content": "str"}},
            {"method": "POST", "path": "/api/upload_file", "auth": True, "body": "multipart: uuid, path, file"},
            {"method": "POST", "path": "/api/delete_file", "auth": True, "body": {"uuid": "str", "path": "str"}},
            {"method": "POST", "path": "/api/execute_command", "auth": True, "body": {"uuid": "str", "command": "shell cmd (no build)", "cwd": "app", "timeout": 300, "env": {}}, "note": "npm run build FORBIDDEN — use issue_deploy"},
            {"method": "POST", "path": "/api/execute_commands", "auth": True, "body": {"uuid": "str", "commands": [{"command": "str", "cwd": "app"}]}},
            {"method": "POST", "path": "/api/set_env", "auth": True, "body": {"uuid": "str", "env_vars": {}, "merge": True}},
            {"method": "POST", "path": "/api/create_project", "auth": True, "body": {"name": "str (required)", "uuid": "optional", "git_url": "optional", "git_provider": "optional", "branch": "main", "start_command": "optional", "domain": "optional", "env_vars": {}, "deploy": "bool, default false — prefer issue_deploy"}, "response_includes": "uuid, execute_command.body, issue_deploy.body, design_contract_url"},
            {"method": "POST", "path": "/api/issue_deploy", "auth": True, "body": {"uuid": "str"}, "description": "Git pull + docker build + restart — production deploy"},
            {"method": "POST", "path": "/api/start_preview", "auth": True, "body": {"uuid": "str"}, "description": "Fast dev preview (next dev/vite, HMR, ~5s)"},
            {"method": "POST", "path": "/api/stop_preview", "auth": True, "body": {"uuid": "str"}},
            {"method": "GET", "path": "/api/preview_status?uuid=", "auth": True, "description": "preview_url, preview_ready, preview_running"},
            {"method": "GET", "path": "/api/projects/{uuid}/preview/logs/stream?live=1", "auth": "optional", "description": "SSE preview dev server logs"},
            {"method": "POST", "path": "/api/start_service", "auth": True, "body": {"uuid": "str"}},
            {"method": "POST", "path": "/api/stop_service", "auth": True, "body": {"uuid": "str"}},
            {"method": "POST", "path": "/api/set_domain", "auth": True, "body": {"uuid": "str", "domain": "app.example.com"}},
            {"method": "POST", "path": "/api/delete_project", "auth": True, "body": {"uuid": "str"}},
            {"method": "GET", "path": "/api/get_logs?uuid=&lines=200", "auth": True, "description": "Snapshot of deploy/runtime logs"},
            {"method": "GET", "path": "/api/projects/{uuid}/logs/stream?live=1", "auth": "optional", "description": "SSE live deploy logs"},
            {"method": "GET", "path": "/api/agent_status?uuid=", "auth": True, "description": "Syte cloud agent status + agent_proxy_url"},
            {"method": "POST", "path": "/api/agent_warm", "auth": True, "body": {"uuid": "str"}, "description": "Non-blocking, deduplicated runtime prewarm for instant chat"},
            {"method": "POST", "path": "/api/agent_start", "auth": True, "body": {"uuid": "str"}, "description": "Start Syte cloud runtime"},
            {"method": "POST", "path": "/api/agent_stop", "auth": True, "body": {"uuid": "str"}},
            {"method": "POST", "path": "/api/agent_restart", "auth": True, "body": {"uuid": "str"}},
            {"method": "POST", "path": "/api/agent_settings", "auth": True, "body": {"uuid": "str", "model_profile": "syra-nano|syra-base|syra-havy"}},
            {"method": "GET", "path": "/api/agent_logs?uuid=&lines=200", "auth": True, "description": "Syte cloud runtime log snapshot"},
            {"method": "GET", "path": "/api/agent_dashboard", "auth": True, "description": "DPFA/MNOA metrics + onboarding state"},
            {"method": "POST", "path": "/api/agent_test", "auth": True, "body": {"uuid": "str"}, "description": "Probe CLI + bridge + communicate"},
            {"method": "POST", "path": "/api/agent_communicate", "auth": True, "body": {"uuid": "str", "message": "str", "model_profile": "optional"}},
            {"method": "POST", "path": "/api/agent_change", "auth": True, "body": {"uuid": "str", "message": "str", "model_profile": "optional", "model_name": "optional"}, "description": "Async code change — returns request_id immediately; use activity stream for live updates"},
            {"method": "GET", "path": "/api/agent_activity?uuid=&since_id=0", "auth": True, "description": "Agent activity snapshot (incremental with since_id)"},
            {"method": "GET", "path": "/api/projects/{uuid}/agent/activity/stream?live=1&since_id=0", "auth": "optional", "description": "SSE real-time agent activity — format=sse|tagged|text|jsonl, types= filter"},
            {"method": "GET", "path": "/api/projects/{uuid}/agent/logs/stream?live=1", "auth": "optional", "description": "SSE Syte cloud agent logs"},
            {"method": "POST", "path": "/api/tokens", "auth": False, "body": {"name": "str"}, "description": "Create API key (GUI)"},
        ],
        "agent_session": {
            "description": (
                "Continuous per-workspace Syte cloud runtime runtime. One durable session per project; "
                "change requests are async jobs that return request_id immediately."
            ),
            "documentation": f"{base}/api/#agent" if base else "/api/#agent",
            "model_profiles": {
                "syra-nano": "Fast — Gemini Flash class",
                "syra-base": "Balanced — DeepSeek chat class",
                "syra-havy": "Capable — Gemini Pro class",
            },
            "gui_configuration": "Syte GUI → AI tab — internal secret + per-profile Verted/DeepSeek API keys",
            "metrics": {
                "dpfa": "Dedicated Performance For Agents — CPU percent on VM",
                "mnoa": "Maximum Number Of Agents — running agents vs configured max",
            },
            "async_change_request": {
                "description": "Default for sycord.com and POST /api/agent_change — non-blocking",
                "submit": "POST /api/agent_change or POST /sycord/api/agent_change {uuid, message, model_profile?}",
                "immediate_response": {
                    "ok": True,
                    "request_id": "req_abc123def456",
                    "status": "accepted",
                    "stream_url": "/api/projects/{uuid}/agent/activity/stream?live=1",
                },
                "legacy_sync": "POST with ?wait=1 on /sycord/api/agent_change or POST /api/agent_communicate for blocking reply",
            },
            "sycord_change_flow": [
                "1. User requests code change on sycord.com",
                "2. Prewarm with POST /api/agent_warm {uuid}; the supervisor keeps used agents alive",
                "3. sycord.com opens SSE GET /api/projects/{uuid}/agent/activity/stream?live=1&since_id=N (or internal route with X-Syra-Internal-Secret)",
                "4. sycord.com POST /sycord/api/agent_change {uuid, message, model_profile} — returns request_id immediately",
                "5. Syte emits request_started -> processing -> [thinking] -> (tool_call_started/tool_call_finished)* -> request_completed|request_failed on SSE; correlate by payload.request_id",
                "6. The durable request runs serialized per project against the persistent Syte cloud conversation",
                "7. Each persisted agent_event is broadcast as a JSON, tagged, text, or JSONL activity record (SSE transport only; there is no WebSocket)",
            ],
            "activity_api": {
                "description": "Real-time Cursor-like chat feed — structured events, not raw logs",
                "snapshot": "GET /api/agent_activity?uuid=&since_id=0",
                "stream": "GET /api/projects/{uuid}/agent/activity/stream?live=1&since_id=0",
                "stream_formats": {
                    "default": "?format=sse (default) — SSE data: {\"type\":\"activity\",\"event\":{...}}; activity frames carry an id: line",
                    "tagged": "?format=tagged — SSE [start]<json>, [processing]<json>, [think]<json>, [tool:start]<json>, [tool:result]<json>, [done]<json>",
                    "text": "?format=text — plain [assistant]/[file]/[cmd]/[thinking] lines (fetch/curl, not EventSource)",
                    "jsonl": "?format=jsonl — one JSON object per line (application/x-ndjson) for CLI consumers",
                },
                "control_frames": {
                    "session": "emitted once when live=1",
                    "ping": "heartbeat every 10s with current since_id",
                    "reconnect": "terminal hint after the 3600s per-connection deadline; reopen with the given since_id",
                    "retry": "one-time SSE retry: 5000 backoff directive for EventSource",
                },
                "reconnection": "Record the highest event.id; reconnect with since_id=<id> or the Last-Event-ID header for gapless, duplicate-free resume (events persist before broadcast)",
                "turn_lifecycle": "request_started -> processing -> [thinking] -> (tool_call_started -> tool_call_finished)* -> request_completed|request_failed; correlate by payload.request_id",
                "note_reserved_events": "token_delta and message_snapshot are valid event types reserved for a future token-streaming provider; the current non-streaming runtime does not emit them",
                "sycord_snapshot": "GET /sycord/api/agent_activity?uuid=&since_id=0",
                "sycord_status": "GET /sycord/api/agent_status?uuid=",
                "internal_snapshot": "GET /api/internal/projects/{uuid}/agent/activity?since_id=0",
                "internal_stream": "GET /api/internal/projects/{uuid}/agent/activity/stream?live=1",
                "event_types": [
                    "user_message",
                    "assistant_message",
                    "token_delta",
                    "message_snapshot",
                    "thinking",
                    "processing",
                    "tool_call",
                    "tool_call_finished",
                    "command_run",
                    "command_output",
                    "file_created",
                    "file_modified",
                    "file_deleted",
                    "file_read",
                    "file_search",
                    "request_started",
                    "request_completed",
                    "request_failed",
                    "agent_started",
                    "agent_stopped",
                ],
                "sse_format": 'data: {"type":"activity","event":{...}}',
                "reconnect": "Pass since_id=last_event_id on snapshot or stream reconnect to avoid gaps",
                "tagged_vocabulary": [
                    "[start]", "[processing]", "[think]", "[tool:start]",
                    "[tool:result]", "[delta]", "[message]", "[done]",
                    "[error]", "[status]", "[session]", "[ping]",
                ],
            },
            "workflow": [
                "1. GET /api/agent_status?uuid= — check agent_status, agent_running, activity_stream_url",
                "2. POST /api/agent_warm {uuid} when opening a project; returns immediately",
                "3. POST /api/agent_change {uuid, message} — async; save request_id from response",
                "4. GET /api/projects/{uuid}/agent/activity/stream?live=1&since_id=0 — stream processing/thinking/tool + request_completed events",
                "5. POST /api/agent_settings {uuid, model_profile} — switch profile mid-session",
                "6. GET /api/agent_activity?uuid=&since_id=N — poll snapshot if SSE unavailable",
                "7. POST /api/agent_stop {uuid} only when continuous warm service is no longer wanted",
            ],
            "status_fields": [
                "agent_status", "agent_running", "agent_warming", "agent_port", "agent_proxy_url",
                "agent_model_profile", "agent_backend", "agent_workspace_path",
                "agent_log_path", "agent_last_error",
            ],
            "internal_routes": {
                "description": "sycord.com server-to-server — X-Syra-Internal-Secret header",
                "base": f"{base}/api/internal" if base else "/api/internal",
                "endpoints": [
                    "GET /projects/{uuid}/agent",
                    "POST /projects/{uuid}/agent/warm",
                    "POST /projects/{uuid}/agent/start",
                    "POST /projects/{uuid}/agent/stop",
                    "POST /projects/{uuid}/agent/restart",
                    "POST /projects/{uuid}/agent/change",
                    "POST /projects/{uuid}/agent/communicate",
                    "POST /projects/{uuid}/agent/test",
                    "GET /projects/{uuid}/agent/logs",
                    "GET /projects/{uuid}/agent/activity",
                    "GET /projects/{uuid}/agent/activity/stream?live=1",
                    "GET|POST /projects/{uuid}/agent/proxy[/{path}]",
                ],
            },
            "errors": {
                "agent_not_running": "Start agent before communicate/proxy",
                "agent_start_failed": "Syte cloud runtime not installed or configuration invalid",
                "backend_unreachable": "Provider API base not reachable",
                "cloud_runtime_not_installed": "Install the project's Python dependencies",
                "internal_secret_not_configured": "Set syra_internal_secret in Settings → Keys",
            },
        },
        "create_project_response": {
            "description": "AI agents: use execute_command for lint/install only; deploy via issue_deploy.body",
            "fields": {
                "uuid": "project id for all subsequent API calls",
                "design_contract": "GET /api/ai.json → design_contract — mandatory UI rules",
                "system_prompt": "GET /api/ai.json → system_prompt — inject as AI system instruction",
                "execute_command": "scaffolding + npm install + npm run lint ONLY",
                "issue_deploy": "POST /api/issue_deploy — git pull + docker build + start",
                "validate_design": "GET /api/validate_design?uuid= — run after generation",
            },
            "example": {
                "ok": True,
                "uuid": "my-site-a1b2c3",
                "status": "created",
                "execute_command": {
                    "method": "POST",
                    "path": "/api/execute_command",
                    "body": {"uuid": "my-site-a1b2c3", "command": "npm run lint", "cwd": "app", "timeout": 300},
                },
                "issue_deploy": {"method": "POST", "path": "/api/issue_deploy", "body": {"uuid": "my-site-a1b2c3"}},
            },
        },
        "execute_command_examples": [
            {"command": "npm install", "cwd": "app", "purpose": "install dependencies"},
            {"command": "npm run lint", "cwd": "app", "purpose": "bug testing — allowed"},
            {"command": "ls -la", "cwd": "app", "purpose": "inspect files"},
            {"command": "mkdir -p src/components/ui", "cwd": "app", "purpose": "scaffold"},
            {"command": "npx create-next-app@latest . --yes", "cwd": "app", "purpose": "scaffold Next.js"},
        ],
        "execute_command_forbidden": [
            "npm run build",
            "yarn build",
            "pnpm build",
            "next build",
            "Use POST /api/issue_deploy {uuid} for all builds",
        ],
        "sycord_api": {
            "description": (
                "Separate integration API for Sycord websites and external projects. "
                "project_connect returns uuid — your app MUST persist it before any other call."
            ),
            "base_url": f"{base}/sycord/api" if base else "/sycord/api",
            "documentation": f"{base}/sycord/api/" if base else "/sycord/api/",
            "integration_guide": f"{base}/sycord/api/integration.json" if base else "/sycord/api/integration.json",
            "spec": f"{base}/sycord/api/spec.json" if base else "/sycord/api/spec.json",
            "uuid_persistence": {
                "required": True,
                "response_field": "uuid",
                "also_in": ["persist.uuid", "project.uuid", "next_steps.save_uuid"],
                "instruction": "Save uuid in your database after project_connect. Required for upload, preview, issue_deployment, container_get, domain, and agent_* calls.",
                "optional_custom_uuid": "Pass body.uuid on project_connect to use your own id",
            },
            "stacks": ["nextjs", "python", "javascript", "html5"],
            "workflow": [
                "1. POST /sycord/api/project_connect {name, stack} → SAVE response.uuid",
                "2. POST /sycord/api/upload — multipart file upload (uuid required)",
                "3. POST /sycord/api/preview_start {uuid} — fast dev preview with HMR",
                "4. GET /sycord/api/preview_status?uuid= — poll until preview_ready=true",
                "5. POST /sycord/api/agent_change {uuid, message} — async AI code change; stream activity",
                "6. GET /sycord/api/agent_activity?uuid=&since_id= — poll or use SSE stream_url",
                "7. POST /sycord/api/issue_deployment {uuid} — docker build + deploy",
                "8. GET /sycord/api/container_get?uuid= — container status",
                "9. POST /sycord/api/domain {uuid, domain} — optional custom domain",
            ],
            "agent_integration": {
                "description": "Sycord backend uses same API token as other /sycord/api routes",
                "status": "GET /sycord/api/agent_status?uuid=",
                "submit_change": "POST /sycord/api/agent_change {uuid, message, model_profile?, wait?}",
                "activity_snapshot": "GET /sycord/api/agent_activity?uuid=&since_id=0",
                "activity_stream": "GET /api/projects/{uuid}/agent/activity/stream?live=1&since_id=0 (SSE; api_key query optional)",
                "async_response": {"ok": True, "request_id": "req_…", "status": "accepted", "stream_url": "/api/projects/{uuid}/agent/activity/stream?live=1"},
            },
            "project_connect_response": {
                "save": "uuid",
                "example_fields": ["uuid", "persist", "project", "next_steps.save_uuid"],
            },
            "endpoints": [
                {"method": "POST", "path": "/sycord/api/project_connect", "auth": True, "returns_uuid": True},
                {"method": "GET", "path": "/sycord/api/container_get?uuid=", "auth": True},
                {"method": "POST", "path": "/sycord/api/upload", "auth": True},
                {"method": "POST", "path": "/sycord/api/preview_start", "auth": True},
                {"method": "GET", "path": "/sycord/api/preview_status?uuid=", "auth": True},
                {"method": "POST", "path": "/sycord/api/preview_stop", "auth": True},
                {"method": "GET", "path": "/sycord/api/agent_status?uuid=", "auth": True},
                {"method": "POST", "path": "/sycord/api/agent_change", "auth": True, "description": "Async code change — returns request_id"},
                {"method": "GET", "path": "/sycord/api/agent_activity?uuid=&since_id=", "auth": True},
                {"method": "POST", "path": "/sycord/api/domain", "auth": True},
                {"method": "POST", "path": "/sycord/api/issue_deployment", "auth": True},
                {"method": "GET", "path": "/sycord/api/spec.json", "auth": False},
                {"method": "GET", "path": "/sycord/api/integration.json", "auth": False},
            ],
        },
    }
