"""Auto-configure dev servers for Syte preview domains (Vite allowedHosts, Next.js origins)."""

import json
import re
from pathlib import Path

from syte.nextjs_layout import is_nextjs_repo
from syte.preview_domains import preview_frame_ancestors_csp


def _vite_frame_headers_block() -> str:
    csp = preview_frame_ancestors_csp()
    return (
        "    headers: {\n"
        f'      "Content-Security-Policy": "{csp}",\n'
        "    },\n"
    )


def is_vite_repo(repo: Path) -> bool:
    pkg = repo / "package.json"
    if not pkg.exists():
        return False
    try:
        data = json.loads(pkg.read_text())
    except (json.JSONDecodeError, OSError):
        return False
    deps = {**data.get("dependencies", {}), **data.get("devDependencies", {})}
    scripts = " ".join(data.get("scripts", {}).values()).lower()
    return "vite" in deps or "vite" in scripts


def prepare_preview_hosts(repo: Path, preview_domain: str) -> list[str]:
    """Patch or generate dev config so preview hostname is allowed behind Caddy."""
    actions: list[str] = []
    if is_vite_repo(repo):
        actions.extend(_ensure_vite_preview(repo))
    if is_nextjs_repo(repo):
        actions.extend(_ensure_nextjs_preview(repo, preview_domain))
    return actions


def build_preview_command(repo: Path, cmd_template: str) -> str:
    """Return dev command; use static vite overlay only when in-place patch is impossible."""
    overlay = repo / "vite.config.syte.mjs"
    if overlay.exists():
        return "npx vite --config vite.config.syte.mjs --host 0.0.0.0 --port $SYTE_PREVIEW_PORT"
    if not is_vite_repo(repo):
        return cmd_template
    if _vite_hosts_configured(repo) or _patch_vite_config_files(repo):
        return cmd_template
    user_config = _find_vite_config_name(repo)
    if user_config:
        _write_vite_static_overlay(repo, user_config)
        return "npx vite --config vite.config.syte.mjs --host 0.0.0.0 --port $SYTE_PREVIEW_PORT"
    return cmd_template


def _vite_hosts_configured(repo: Path) -> bool:
    for name in ("vite.config.js", "vite.config.mjs", "vite.config.ts"):
        path = repo / name
        if not path.exists():
            continue
        text = path.read_text()
        if re.search(r"allowedHosts\s*:\s*true", text) and "frame-ancestors" in text:
            return True
    overlay = repo / "vite.config.syte.mjs"
    if overlay.exists() and "frame-ancestors" in overlay.read_text():
        return True
    return False


def _find_vite_config_name(repo: Path) -> str | None:
    for name in ("vite.config.ts", "vite.config.js", "vite.config.mjs"):
        if (repo / name).exists():
            return name
    return None


def _write_vite_static_overlay(repo: Path, user_config: str) -> Path:
    """Wrap a specific user vite config — static import avoids esbuild glob on Tailwind CSS."""
    overlay = repo / "vite.config.syte.mjs"
    overlay.write_text(
        "// Auto-generated by Syte — allows preview*.sycord.site via Caddy\n"
        "import { mergeConfig } from 'vite';\n"
        f"import base from './{user_config}';\n"
        "\n"
        "const resolved = typeof base === 'function'\n"
        "  ? await base({ command: 'serve', mode: 'development' })\n"
        "  : (base?.default ?? base);\n"
        "\n"
        "export default mergeConfig(resolved, {\n"
        "  server: {\n"
        "    host: true,\n"
        "    allowedHosts: true,\n"
        f"{_vite_frame_headers_block()}"
        "  },\n"
        "});\n"
    )
    return overlay


def _ensure_vite_preview(repo: Path) -> list[str]:
    overlay = repo / "vite.config.syte.mjs"
    if overlay.exists() and "frame-ancestors" not in overlay.read_text():
        overlay.unlink()

    actions = _patch_vite_config_files(repo)
    if actions:
        _remove_stale_vite_overlay(repo)
        return actions
    user_config = _find_vite_config_name(repo)
    if user_config:
        path = _write_vite_static_overlay(repo, user_config)
        return [f"Wrote {path.name} wrapping {user_config} (server.allowedHosts: true)"]
    return ["No vite.config found; dev command will use --host flags only"]


def _remove_stale_vite_overlay(repo: Path) -> None:
    overlay = repo / "vite.config.syte.mjs"
    if overlay.exists():
        overlay.unlink()


def _patch_vite_config_files(repo: Path) -> list[str]:
    """Also patch existing vite.config so npm run dev works without overlay."""
    actions: list[str] = []
    for name in ("vite.config.js", "vite.config.mjs", "vite.config.ts"):
        path = repo / name
        if not path.exists():
            continue
        text = path.read_text()
        if re.search(r"allowedHosts\s*:\s*true", text) and "frame-ancestors" in text:
            continue
        new_text = _inject_vite_allowed_hosts(text)
        if new_text != text:
            path.write_text(new_text)
            actions.append(f"Patched {name}: server.allowedHosts = true")
    return actions


def _inject_vite_allowed_hosts(text: str) -> str:
    headers = _vite_frame_headers_block()
    if re.search(r"allowedHosts\s*:", text):
        text = re.sub(
            r"allowedHosts\s*:\s*(?:\[[^\]]*\]|'[^']*'|\"[^\"]*\"|\S+)",
            "allowedHosts: true",
            text,
            count=1,
        )
    elif re.search(r"server\s*:\s*\{", text):
        text = re.sub(
            r"(server\s*:\s*\{)",
            rf"\1\n    host: true,\n    allowedHosts: true,\n{headers}",
            text,
            count=1,
        )
    elif re.search(r"defineConfig\s*\(\s*\{", text):
        text = re.sub(
            r"defineConfig\s*\(\s*\{",
            f"defineConfig({{\n  server: {{ host: true, allowedHosts: true,\n{headers}  }},",
            text,
            count=1,
        )
    elif "export default {" in text:
        text = re.sub(
            r"export default \{",
            f"export default {{\n  server: {{ host: true, allowedHosts: true,\n{headers}  }},",
            text,
            count=1,
        )
    if "frame-ancestors" not in text and re.search(r"server\s*:\s*\{", text):
        text = re.sub(
            r"(server\s*:\s*\{)",
            rf"\1\n{headers}",
            text,
            count=1,
        )
    return text


def _ensure_nextjs_preview(repo: Path, preview_domain: str) -> list[str]:
    actions: list[str] = []
    for name in ("next.config.mjs", "next.config.js", "next.config.ts"):
        path = repo / name
        if not path.exists():
            continue
        text = path.read_text()
        if preview_domain in text and "allowedDevOrigins" in text:
            return actions
        new_text = _inject_next_allowed_origins(text, preview_domain)
        if new_text != text:
            path.write_text(new_text)
            actions.append(f"Patched {name}: allowedDevOrigins for {preview_domain}")
        return actions
    return actions


def _inject_next_allowed_origins(text: str, preview_domain: str) -> str:
    host_entry = f'"{preview_domain}"'
    https_entry = f'"https://{preview_domain}"'
    if "allowedDevOrigins" in text:
        if preview_domain in text:
            return text
        return re.sub(
            r"allowedDevOrigins\s*:\s*\[",
            f"allowedDevOrigins: [{host_entry}, {https_entry}, ",
            text,
            count=1,
        )
    if "module.exports" in text and "module.exports =" in text:
        return re.sub(
            r"module\.exports\s*=\s*\{",
            f"module.exports = {{\n  allowedDevOrigins: [{host_entry}, {https_entry}],",
            text,
            count=1,
        )
    if "export default" in text:
        return re.sub(
            r"export default\s*\{",
            f"export default {{\n  allowedDevOrigins: [{host_entry}, {https_entry}],",
            text,
            count=1,
        )
    return text
