"""Auto-configure dev servers for Syte preview domains (Vite allowedHosts, Next.js origins)."""

import json
import re
from pathlib import Path

from syte.nextjs_layout import is_nextjs_repo


def is_vite_repo(repo: Path) -> bool:
    pkg = repo / "package.json"
    if not pkg.exists():
        return False
    try:
        data = json.loads(pkg.read_text())
    except (json.JSONDecodeError, OSError):
        return False
    deps = {**data.get("dependencies", {}), **data.get("devDependencies", {})}
    scripts = " ".join(data.get("scripts", {}).values()).lower()
    return "vite" in deps or "vite" in scripts


def prepare_preview_hosts(repo: Path, preview_domain: str) -> list[str]:
    """Patch or generate dev config so preview hostname is allowed behind Caddy."""
    actions: list[str] = []
    if is_vite_repo(repo):
        actions.extend(_ensure_vite_preview(repo))
    if is_nextjs_repo(repo):
        actions.extend(_ensure_nextjs_preview(repo, preview_domain))
    return actions


def build_preview_command(repo: Path, cmd_template: str) -> str:
    """Use Syte vite overlay config when project is Vite-based."""
    if is_vite_repo(repo):
        _write_vite_overlay_config(repo)
        return "npx vite --config vite.config.syte.mjs --host 0.0.0.0 --port $SYTE_PREVIEW_PORT"
    return cmd_template


def _write_vite_overlay_config(repo: Path) -> Path:
    """Merge user vite config + server.allowedHosts: true for all preview domains."""
    overlay = repo / "vite.config.syte.mjs"
    overlay.write_text(
        "// Auto-generated by Syte — allows preview*.sycord.site via Caddy\n"
        "import { defineConfig, mergeConfig } from 'vite';\n"
        "\n"
        "async function loadBase() {\n"
        "  for (const file of ['vite.config.ts', 'vite.config.js', 'vite.config.mjs']) {\n"
        "    try {\n"
        "      const mod = await import(`./${file}`);\n"
        "      return mod.default ?? mod;\n"
        "    } catch { /* try next */ }\n"
        "  }\n"
        "  return {};\n"
        "}\n"
        "\n"
        "const base = await loadBase();\n"
        "\n"
        "export default mergeConfig(base, {\n"
        "  server: {\n"
        "    host: true,\n"
        "    allowedHosts: true,\n"
        "  },\n"
        "});\n"
    )
    return overlay


def _ensure_vite_preview(repo: Path) -> list[str]:
    path = _write_vite_overlay_config(repo)
    actions = [f"Wrote {path.name} with server.allowedHosts: true"]
    actions.extend(_patch_vite_config_files(repo))
    return actions


def _patch_vite_config_files(repo: Path) -> list[str]:
    """Also patch existing vite.config so npm run dev works without overlay."""
    actions: list[str] = []
    for name in ("vite.config.js", "vite.config.mjs", "vite.config.ts"):
        path = repo / name
        if not path.exists():
            continue
        text = path.read_text()
        if re.search(r"allowedHosts\s*:\s*true", text):
            continue
        new_text = _inject_vite_allowed_hosts(text)
        if new_text != text:
            path.write_text(new_text)
            actions.append(f"Patched {name}: server.allowedHosts = true")
    return actions


def _inject_vite_allowed_hosts(text: str) -> str:
    if re.search(r"allowedHosts\s*:", text):
        return re.sub(
            r"allowedHosts\s*:\s*(?:\[[^\]]*\]|'[^']*'|\"[^\"]*\"|\S+)",
            "allowedHosts: true",
            text,
            count=1,
        )
    if re.search(r"server\s*:\s*\{", text):
        return re.sub(
            r"(server\s*:\s*\{)",
            r"\1\n    host: true,\n    allowedHosts: true,",
            text,
            count=1,
        )
    if re.search(r"defineConfig\s*\(\s*\{", text):
        return re.sub(
            r"defineConfig\s*\(\s*\{",
            "defineConfig({\n  server: { host: true, allowedHosts: true },",
            text,
            count=1,
        )
    if "export default {" in text:
        return re.sub(
            r"export default \{",
            "export default {\n  server: { host: true, allowedHosts: true },",
            text,
            count=1,
        )
    return text


def _ensure_nextjs_preview(repo: Path, preview_domain: str) -> list[str]:
    actions: list[str] = []
    for name in ("next.config.mjs", "next.config.js", "next.config.ts"):
        path = repo / name
        if not path.exists():
            continue
        text = path.read_text()
        if preview_domain in text and "allowedDevOrigins" in text:
            return actions
        new_text = _inject_next_allowed_origins(text, preview_domain)
        if new_text != text:
            path.write_text(new_text)
            actions.append(f"Patched {name}: allowedDevOrigins for {preview_domain}")
        return actions
    return actions


def _inject_next_allowed_origins(text: str, preview_domain: str) -> str:
    host_entry = f'"{preview_domain}"'
    https_entry = f'"https://{preview_domain}"'
    if "allowedDevOrigins" in text:
        if preview_domain in text:
            return text
        return re.sub(
            r"allowedDevOrigins\s*:\s*\[",
            f"allowedDevOrigins: [{host_entry}, {https_entry}, ",
            text,
            count=1,
        )
    if "module.exports" in text and "module.exports =" in text:
        return re.sub(
            r"module\.exports\s*=\s*\{",
            f"module.exports = {{\n  allowedDevOrigins: [{host_entry}, {https_entry}],",
            text,
            count=1,
        )
    if "export default" in text:
        return re.sub(
            r"export default\s*\{",
            f"export default {{\n  allowedDevOrigins: [{host_entry}, {https_entry}],",
            text,
            count=1,
        )
    return text
