"use client";

import { FormEvent, useState } from "react";
import { ArrowRight, CircleDot, Cloud, FileCode2, Globe2, KeyRound, LayoutDashboard, Loader2, LockKeyhole, LogOut, Play, Rocket, Server, ShieldCheck, SlidersHorizontal, Square, TerminalSquare } from "lucide-react";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { Input } from "../components/ui/input";

type Overview = { instance: { id: string; status: string }; project: { id: string; name: string; domain: string; status: string; running: boolean; url: string; created_at?: string; variables: number } };
type View = "landing" | "login" | "dashboard" | "terminal" | "files" | "startup" | "network" | "access";
const nav = [{ key: "dashboard", label: "Console", icon: LayoutDashboard }, { key: "terminal", label: "Terminal", icon: TerminalSquare }, { key: "files", label: "Files", icon: FileCode2 }, { key: "startup", label: "Startup", icon: SlidersHorizontal }, { key: "network", label: "Network", icon: Globe2 }, { key: "access", label: "Access", icon: KeyRound }] as const;

export default function ControlPlane({ initialOverview, authenticated }: { initialOverview: Overview | null; authenticated: boolean }) {
  const [view, setView] = useState<View>(authenticated ? "dashboard" : "landing");
  const [overview, setOverview] = useState<Overview | null>(initialOverview);
  const [password, setPassword] = useState("");
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState<string | null>(null);
  const [terminal, setTerminal] = useState("Control Plane terminal ready. Run status, logs, or health.");
  const project = overview?.project;

  async function refresh() { const r = await fetch("/api/control", { cache: "no-store" }); const data = await r.json(); if (!r.ok) throw new Error(data.error || "Unable to load workspace"); setOverview(data); return data; }
  async function signIn(event: FormEvent) { event.preventDefault(); setBusy("login"); setNotice(""); try { const r = await fetch("/api/access", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ password }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error || "Access was not granted"); await refresh(); setPassword(""); setView("dashboard"); } catch (e) { setNotice(e instanceof Error ? e.message : "Unable to sign in"); } finally { setBusy(null); } }
  async function action(name: "start" | "stop" | "deploy") { setBusy(name); setNotice(""); try { const r = await fetch("/api/control", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: name }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error || "Operation failed"); setNotice(data.message || "Operation queued"); await refresh(); } catch (e) { setNotice(e instanceof Error ? e.message : "Operation failed"); } finally { setBusy(null); } }
  async function runTerminal(command: "status" | "logs" | "health") { setBusy(command); try { const r = await fetch("/api/terminal", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ command }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error || "Terminal request failed"); setTerminal(`$ ${command}\n${data.output}`); } catch (e) { setTerminal(`$ ${command}\n${e instanceof Error ? e.message : "Terminal request failed"}`); } finally { setBusy(null); } }
  async function signOut() { await fetch("/api/access", { method: "DELETE" }); setOverview(null); setView("landing"); setNotice(""); }

  if (view === "landing") return <main className="reference-landing"><nav className="reference-topbar"><div className="reference-mark"><span>CP</span><b>CONTROL PLANE</b></div><Button variant="ghost" size="sm" onClick={() => setView("login")}>Sign in <ArrowRight size={14}/></Button></nav><section className="reference-landing-card"><div className="reference-editorial"><div className="reference-grid"/><div className="reference-pulse"><span className="pulse-dot"/>Production service<br/><b>Project-scoped access</b></div><div className="reference-editorial-copy"><p>SYTE HOSTED CONTROL</p><h1>Everything your project needs.<br/>Nothing it does not.</h1><span>Live operations, files, runtime configuration, and access — all kept inside one secure workspace.</span></div></div><div className="reference-landing-side"><p className="reference-kicker">CONTROL PLANE</p><h2>Operate your hosted service with clarity.</h2><p>Use a dedicated workspace to deploy, inspect runtime output, manage source files, and protect access to this one Syte project.</p><div className="reference-benefits"><span><ShieldCheck size={15}/> Scoped by project</span><span><TerminalSquare size={15}/> Live runtime output</span><span><LockKeyhole size={15}/> Server-only platform key</span></div><Button size="lg" onClick={() => setView("login")}>Open workspace <ArrowRight size={16}/></Button></div></section></main>;

  if (view === "login") return <main className="reference-auth"><section className="reference-auth-card"><aside className="reference-auth-art"><div className="reference-auth-brand"><span>CP</span><b>CONTROL PLANE</b></div><div className="reference-art-grid"/><div className="reference-art-status"><span className="pulse-dot"/> Hosted service is ready</div><div className="reference-auth-art-copy"><p>SYTE HOSTED WORKSPACE</p><h1>One clear place<br/>to run your service.</h1><span>Deploy, inspect, and protect your project without exposing infrastructure credentials.</span></div></aside><section className="reference-auth-form"><div><p className="reference-kicker">WELCOME BACK</p><h2>Sign in to your workspace</h2><p className="reference-form-copy">Use the workspace access password chosen by the project owner during provisioning.</p></div><form onSubmit={signIn} className="reference-form"><label>Workspace access password<Input type="password" minLength={12} value={password} onChange={e => setPassword(e.target.value)} placeholder="Enter your access password" autoFocus required/></label>{notice && <p className="form-notice">{notice}</p>}<Button type="submit" disabled={busy === "login"}>{busy === "login" && <Loader2 className="spin" size={15}/>}Continue to workspace <ArrowRight size={15}/></Button><div className="reference-divider"><span>SECURE PROJECT ACCESS</span></div><p className="reference-form-foot">This session can operate only the Syte project assigned to this Control Plane workspace.</p><button type="button" className="reference-back" onClick={() => setView("landing")}>← Back to overview</button></form></section></section></main>;

  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span>CP</span><div><b>Control Plane</b><small>{project?.name || "Protected workspace"}</small></div></div><nav>{nav.map(item => { const Icon = item.icon; return <button key={item.key} className={view === item.key ? "nav-link active" : "nav-link"} onClick={() => setView(item.key)}><Icon size={16}/>{item.label}</button>; })}</nav><div className="sidebar-footer"><CircleDot size={14}/><span>Scoped workspace</span><Button variant="ghost" size="icon" aria-label="Sign out" onClick={signOut}><LogOut size={15}/></Button></div></aside><section className="workspace"><header className="workspace-head"><div><p>Syte hosted project</p><h1>{project?.name || "Control Plane"}</h1></div><Button variant="outline" size="sm" onClick={() => refresh().catch(e => setNotice(e.message))}>Refresh</Button></header>{notice && <div className="form-notice">{notice}</div>}{view === "dashboard" && <Dashboard project={project} overview={overview} busy={busy} action={action}/>} {view === "terminal" && <Terminal output={terminal} busy={busy} run={runTerminal}/>} {view === "files" && <Files/>} {view === "startup" && <Startup/>} {view === "network" && <Network project={project}/>} {view === "access" && <Access project={project} signOut={signOut}/>}</section></main>;
}

function Dashboard({ project, overview, busy, action }: { project?: Overview["project"]; overview: Overview | null; busy: string | null; action: (name: "start" | "stop" | "deploy") => Promise<void> }) { return <><section className="hero-card"><div><span className={project?.running ? "status online" : "status"}>{project?.running ? "Production online" : "Service stopped"}</span><h2>{project?.domain || "Server ready for domain setup"}</h2><p>Lifecycle controls operate only the project bound to this workspace.</p></div><div className="actions"><Button variant="secondary" onClick={() => action("deploy")} disabled={!!busy}>{busy === "deploy" ? <Loader2 className="spin" size={15}/> : <Cloud size={15}/>}Deploy latest</Button>{project?.running ? <Button variant="destructive" onClick={() => action("stop")} disabled={!!busy}><Square size={14}/>Stop server</Button> : <Button onClick={() => action("start")} disabled={!!busy}><Play size={15}/>Start server</Button>}</div></section><section className="metric-grid"><Metric label="Server state" value={project?.running ? "Online" : "Stopped"} note={project?.status || "Waiting"}/><Metric label="Environment" value={String(project?.variables || 0)} note="Configured values"/><Metric label="Access" value="Protected" note="Owner password"/><Metric label="Instance" value={overview?.instance.status || "Ready"} note="Scoped credential"/></section><section className="two-grid"><Card><CardHeader><CardTitle>Production service</CardTitle><CardDescription>Current server assignment</CardDescription></CardHeader><CardContent className="details"><Detail label="Project ID" value={project?.id || "—"}/><Detail label="Domain" value={project?.domain || "Not assigned"}/><Detail label="Status" value={project?.status || "Waiting"}/></CardContent></Card><Card><CardHeader><CardTitle>Next step</CardTitle><CardDescription>Finish your environment</CardDescription></CardHeader><CardContent><p className="muted">Use Startup to review runtime settings, Terminal to validate health, and Network to review the assigned endpoint.</p></CardContent></Card></section></> }
function Files() { const [path, setPath] = useState(""); const [data, setData] = useState<any>(null); const [content, setContent] = useState(""); const [notice, setNotice] = useState(""); const load = async (nextPath = path) => { try { const r = await fetch(`/api/files?path=${encodeURIComponent(nextPath)}`); const body = await r.json(); if (!r.ok) throw new Error(body.error || "Could not open project files"); setPath(body.path || ""); setData(body); setContent(body.content || ""); } catch (e) { setNotice(e instanceof Error ? e.message : "Could not open project files"); } }; const save = async () => { try { const r = await fetch("/api/files", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ path, content }) }); const body = await r.json(); if (!r.ok) throw new Error(body.error || "Could not save project file"); setNotice(body.message); } catch (e) { setNotice(e instanceof Error ? e.message : "Could not save project file"); } }; return <section className="hosting-block"><header><div><p>Project files</p><h2>Files</h2></div><Button size="sm" variant="outline" onClick={() => load("")}>Open root</Button></header>{notice && <p className="form-notice">{notice}</p>}<div className="file-layout"><Card><CardHeader><CardTitle>Workspace</CardTitle><CardDescription>Only files inside this hosted project are available.</CardDescription></CardHeader><CardContent className="file-list">{data?.type === "folder" ? data.entries.map((item: any) => <button key={item.path} onClick={() => load(item.path)}><span>{item.type === "folder" ? "▸" : "·"}</span>{item.name}<small>{item.type}</small></button>) : <Button variant="outline" onClick={() => load("")}>Back to folder</Button>}{!data && <Button onClick={() => load("")}>Load project files</Button>}</CardContent></Card><Card><CardHeader><CardTitle>{data?.type === "file" ? path : "Select a file"}</CardTitle><CardDescription>Edits are written to the project workspace and take effect after deploy.</CardDescription></CardHeader><CardContent className="stack">{data?.type === "file" ? <><textarea className="code-editor" value={content} onChange={e => setContent(e.target.value)}/><Button onClick={save}>Save project file</Button></> : <p className="muted">Open a text file from the workspace list to edit it.</p>}</CardContent></Card></div></section> }
function Startup() { const [config, setConfig] = useState<any>(null); const [message, setMessage] = useState(""); const load = async () => { const r = await fetch("/api/startup"); const data = await r.json(); if (!r.ok) return setMessage(data.error || "Unable to load startup settings"); setConfig(data); }; const save = async (event: FormEvent) => { event.preventDefault(); const r = await fetch("/api/startup", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(config) }); const data = await r.json(); setMessage(r.ok ? "Startup settings saved. Deploy to apply them." : data.error || "Unable to save settings"); if (r.ok) setConfig(data); }; return <section className="hosting-block"><header><div><p>Runtime configuration</p><h2>Startup</h2></div><Button variant="outline" size="sm" onClick={load}>Load settings</Button></header>{message && <p className="form-notice">{message}</p>}<Card><CardHeader><CardTitle>Service startup</CardTitle><CardDescription>These settings apply only to this hosted project.</CardDescription></CardHeader><CardContent>{config ? <form className="stack" onSubmit={save}><label>Startup command<Input value={config.start_command || ""} onChange={e => setConfig({ ...config, start_command: e.target.value })}/></label><label>Health check path<Input value={config.healthcheck_path || "/"} onChange={e => setConfig({ ...config, healthcheck_path: e.target.value })}/></label><Detail label="Deploy type" value={config.deploy_type}/><Detail label="Public port" value={String(config.port)}/><Button type="submit">Save runtime settings</Button></form> : <Button onClick={load}>Load startup configuration</Button>}</CardContent></Card></section> }
function Network({ project }: { project?: Overview["project"] }) { return <section className="hosting-block"><header><div><p>Endpoint assignment</p><h2>Network</h2></div></header><div className="page-grid"><Card><CardHeader><CardTitle>Primary endpoint</CardTitle><CardDescription>Live public service metadata for this project.</CardDescription></CardHeader><CardContent className="stack"><Detail label="Production domain" value={project?.domain || "Not assigned"}/><Detail label="Service URL" value={project?.url || "Not available"}/><Detail label="Project port" value={project ? "Project-scoped" : "—"}/></CardContent></Card><Card><CardHeader><CardTitle>Network boundary</CardTitle></CardHeader><CardContent><p className="muted">Control Plane exposes only the domain and endpoint assigned to its own Syte project. Domain issuance and DNS remain managed through the Syte console.</p></CardContent></Card></div></section> }
function Terminal({ output, busy, run }: { output: string; busy: string | null; run: (command: "status" | "logs" | "health") => Promise<void> }) { return <section className="terminal-page"><div className="terminal-head"><div><p>Project terminal</p><h2>Operational output</h2></div><div className="actions"><Button variant="outline" size="sm" disabled={!!busy} onClick={() => run("status")}>status</Button><Button variant="outline" size="sm" disabled={!!busy} onClick={() => run("health")}>health</Button><Button variant="outline" size="sm" disabled={!!busy} onClick={() => run("logs")}>logs</Button></div></div><pre className="terminal"><span>control-plane@syte:~$</span> {output}</pre><p className="muted">This project terminal has real, scoped commands for status, health, and logs. Arbitrary host-shell commands are intentionally unavailable.</p></section> }
function Access({ project, signOut }: { project?: Overview["project"]; signOut: () => Promise<void> }) { const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); async function rotate(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); try { const r = await fetch("/api/access", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ currentPassword, newPassword }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error || "Password change failed"); setCurrentPassword(""); setNewPassword(""); setMessage(data.message || "Workspace access password changed."); } catch (e) { setMessage(e instanceof Error ? e.message : "Password change failed"); } finally { setSaving(false); } } return <section className="page-grid"><Card><CardHeader><CardTitle>Workspace access</CardTitle><CardDescription>Users sign in with a dedicated access password; the Syte instance credential remains server-only.</CardDescription></CardHeader><CardContent className="stack"><Detail label="Workspace" value={project?.name || "Control Plane"}/><Detail label="Session" value="Authenticated"/><form className="stack" onSubmit={rotate}><label>Current password<Input type="password" minLength={12} value={currentPassword} onChange={e => setCurrentPassword(e.target.value)} required/></label><label>New password<Input type="password" minLength={12} value={newPassword} onChange={e => setNewPassword(e.target.value)} required/></label>{message && <p className="form-notice">{message}</p>}<Button type="submit" disabled={saving}>{saving && <Loader2 className="spin" size={15}/>}Change access password</Button></form><Button variant="destructive" onClick={signOut}>Sign out of workspace</Button></CardContent></Card><Card><CardHeader><CardTitle>Access boundary</CardTitle></CardHeader><CardContent><p className="muted">The workspace password can be changed here. The scoped Syte credential is never sent to the browser and cannot be viewed or changed from this panel.</p></CardContent></Card></section> }
function Feature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <Card className="feature"><CardHeader><div className="feature-icon">{icon}</div><CardTitle>{title}</CardTitle><CardDescription>{text}</CardDescription></CardHeader></Card> }
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <Card className="metric"><CardContent><p>{label}</p><strong>{value}</strong><span>{note}</span></CardContent></Card> }
function Detail({ label, value }: { label: string; value: string }) { return <div className="detail"><span>{label}</span><b>{value}</b></div> }
