"use client";

import { FormEvent, useState } from "react";
import { Activity, ArrowRight, CircleDot, Cloud, Command, KeyRound, LayoutDashboard, Loader2, LockKeyhole, LogOut, Play, Rocket, Server, ShieldCheck, Square, TerminalSquare, Users } from "lucide-react";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { Input } from "../components/ui/input";

type Overview = { instance: { id: string; status: string }; project: { id: string; name: string; domain: string; status: string; running: boolean; url: string; created_at?: string; variables: number } };
type View = "landing" | "login" | "dashboard" | "setup" | "terminal" | "access";
const nav = [{ key: "dashboard", label: "Dashboard", icon: LayoutDashboard }, { key: "setup", label: "Server setup", icon: Server }, { key: "terminal", label: "Terminal", icon: TerminalSquare }, { key: "access", label: "Access", icon: KeyRound }] as const;

export default function ControlPlane({ initialOverview, authenticated }: { initialOverview: Overview | null; authenticated: boolean }) {
  const [view, setView] = useState<View>(authenticated ? "dashboard" : "landing");
  const [overview, setOverview] = useState<Overview | null>(initialOverview);
  const [password, setPassword] = useState("");
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState<string | null>(null);
  const [terminal, setTerminal] = useState("Control Plane terminal ready. Run status, logs, or health.");
  const project = overview?.project;

  async function refresh() { const r = await fetch("/api/control", { cache: "no-store" }); const data = await r.json(); if (!r.ok) throw new Error(data.error || "Unable to load workspace"); setOverview(data); return data; }
  async function signIn(event: FormEvent) { event.preventDefault(); setBusy("login"); setNotice(""); try { const r = await fetch("/api/access", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ password }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error || "Access was not granted"); await refresh(); setPassword(""); setView("dashboard"); } catch (e) { setNotice(e instanceof Error ? e.message : "Unable to sign in"); } finally { setBusy(null); } }
  async function action(name: "start" | "stop" | "deploy") { setBusy(name); setNotice(""); try { const r = await fetch("/api/control", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: name }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error || "Operation failed"); setNotice(data.message || "Operation queued"); await refresh(); } catch (e) { setNotice(e instanceof Error ? e.message : "Operation failed"); } finally { setBusy(null); } }
  async function runTerminal(command: "status" | "logs" | "health") { setBusy(command); try { const r = await fetch("/api/terminal", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ command }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error || "Terminal request failed"); setTerminal(`$ ${command}\n${data.output}`); } catch (e) { setTerminal(`$ ${command}\n${e instanceof Error ? e.message : "Terminal request failed"}`); } finally { setBusy(null); } }
  async function signOut() { await fetch("/api/access", { method: "DELETE" }); setOverview(null); setView("landing"); setNotice(""); }

  if (view === "landing") return <main className="landing"><nav className="landing-nav"><div className="brand"><span>CP</span><b>Control Plane</b></div><div><Button variant="ghost" size="sm" onClick={() => setView("login")}>Sign in</Button><Button size="sm" onClick={() => setView("login")}>Open workspace <ArrowRight size={14}/></Button></div></nav><section className="landing-hero"><div className="eyebrow"><ShieldCheck size={15}/> Syte-hosted control surface</div><h1>Deploy, operate, and protect your server from one workspace.</h1><p>Control Plane turns your Syte project into a secure operating console with scoped access, live lifecycle controls, and project-bound runtime visibility.</p><div className="landing-actions"><Button size="lg" onClick={() => setView("login")}>Access your workspace <ArrowRight size={16}/></Button><Button size="lg" variant="outline" onClick={() => setView("login")}>Configure access</Button></div></section><section className="feature-grid"><Feature icon={<Rocket/>} title="Deploy on demand" text="Queue a real Syte deployment, start, or stop only this hosted project."/><Feature icon={<TerminalSquare/>} title="Scoped terminal" text="Read current status, health configuration, and live runtime logs without host-shell access."/><Feature icon={<LockKeyhole/>} title="Access by design" text="The platform credential stays server-side; workspace users authenticate with a separate owner password."/></section><footer>Control Plane · hosted securely by Syte</footer></main>;

  if (view === "login") return <main className="auth-page"><Card className="auth-card"><CardHeader><div className="icon-tile"><LockKeyhole/></div><CardTitle>Sign in to Control Plane</CardTitle><CardDescription>Use the workspace access password configured by the project owner in Share It.</CardDescription></CardHeader><CardContent><form onSubmit={signIn} className="stack"><label>Workspace access password<Input type="password" minLength={12} value={password} onChange={e => setPassword(e.target.value)} placeholder="At least 12 characters" autoFocus required/></label>{notice && <p className="form-notice">{notice}</p>}<Button type="submit" disabled={busy === "login"}>{busy === "login" && <Loader2 className="spin" size={15}/>}Unlock workspace</Button><Button type="button" variant="ghost" onClick={() => setView("landing")}>Back to landing</Button></form></CardContent></Card></main>;

  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span>CP</span><div><b>Control Plane</b><small>{project?.name || "Protected workspace"}</small></div></div><nav>{nav.map(item => { const Icon = item.icon; return <button key={item.key} className={view === item.key ? "nav-link active" : "nav-link"} onClick={() => setView(item.key)}><Icon size={16}/>{item.label}</button>; })}</nav><div className="sidebar-footer"><CircleDot size={14}/><span>Scoped workspace</span><Button variant="ghost" size="icon" aria-label="Sign out" onClick={signOut}><LogOut size={15}/></Button></div></aside><section className="workspace"><header className="workspace-head"><div><p>Syte hosted project</p><h1>{project?.name || "Control Plane"}</h1></div><Button variant="outline" size="sm" onClick={() => refresh().catch(e => setNotice(e.message))}>Refresh</Button></header>{notice && <div className="form-notice">{notice}</div>}{view === "dashboard" && <Dashboard project={project} overview={overview} busy={busy} action={action}/>} {view === "setup" && <Setup project={project} busy={busy} action={action}/>} {view === "terminal" && <Terminal output={terminal} busy={busy} run={runTerminal}/>} {view === "access" && <Access project={project} signOut={signOut}/>}</section></main>;
}

function Dashboard({ project, overview, busy, action }: { project?: Overview["project"]; overview: Overview | null; busy: string | null; action: (name: "start" | "stop" | "deploy") => Promise<void> }) { return <><section className="hero-card"><div><span className={project?.running ? "status online" : "status"}>{project?.running ? "Production online" : "Service stopped"}</span><h2>{project?.domain || "Server ready for domain setup"}</h2><p>Lifecycle controls operate only the project bound to this workspace.</p></div><div className="actions"><Button variant="secondary" onClick={() => action("deploy")} disabled={!!busy}>{busy === "deploy" ? <Loader2 className="spin" size={15}/> : <Cloud size={15}/>}Deploy latest</Button>{project?.running ? <Button variant="destructive" onClick={() => action("stop")} disabled={!!busy}><Square size={14}/>Stop server</Button> : <Button onClick={() => action("start")} disabled={!!busy}><Play size={15}/>Start server</Button>}</div></section><section className="metric-grid"><Metric label="Server state" value={project?.running ? "Online" : "Stopped"} note={project?.status || "Waiting"}/><Metric label="Environment" value={String(project?.variables || 0)} note="Configured values"/><Metric label="Access" value="Protected" note="Owner password"/><Metric label="Instance" value={overview?.instance.status || "Ready"} note="Scoped credential"/></section><section className="two-grid"><Card><CardHeader><CardTitle>Production service</CardTitle><CardDescription>Current server assignment</CardDescription></CardHeader><CardContent className="details"><Detail label="Project ID" value={project?.id || "—"}/><Detail label="Domain" value={project?.domain || "Not assigned"}/><Detail label="Status" value={project?.status || "Waiting"}/></CardContent></Card><Card><CardHeader><CardTitle>Next step</CardTitle><CardDescription>Finish your environment</CardDescription></CardHeader><CardContent><p className="muted">Open Server setup to deploy the source, assign a domain in Syte, and validate runtime health.</p></CardContent></Card></section></> }
function Setup({ project, busy, action }: { project?: Overview["project"]; busy: string | null; action: (name: "start" | "stop" | "deploy") => Promise<void> }) { return <section className="page-grid"><Card><CardHeader><CardTitle>Server setup</CardTitle><CardDescription>Run the real deployment lifecycle for this Syte-hosted project.</CardDescription></CardHeader><CardContent className="stack"><Detail label="Project" value={project?.id || "—"}/><Detail label="Production domain" value={project?.domain || "Assign in Syte project settings"}/><Detail label="Service status" value={project?.status || "Waiting"}/><Button onClick={() => action("deploy")} disabled={!!busy}>{busy === "deploy" ? <Loader2 className="spin" size={15}/> : <Rocket size={15}/>}Build and deploy source</Button><Button variant="outline" onClick={() => action(project?.running ? "stop" : "start")} disabled={!!busy}>{project?.running ? "Stop service" : "Start service"}</Button></CardContent></Card><Card><CardHeader><CardTitle>Setup checklist</CardTitle></CardHeader><CardContent className="checklist"><p>1. Build source with Docker.</p><p>2. Assign a production domain in the Syte project settings.</p><p>3. Use Terminal to confirm logs and health configuration.</p></CardContent></Card></section> }
function Terminal({ output, busy, run }: { output: string; busy: string | null; run: (command: "status" | "logs" | "health") => Promise<void> }) { return <section className="terminal-page"><div className="terminal-head"><div><p>Project terminal</p><h2>Operational output</h2></div><div className="actions"><Button variant="outline" size="sm" disabled={!!busy} onClick={() => run("status")}>status</Button><Button variant="outline" size="sm" disabled={!!busy} onClick={() => run("health")}>health</Button><Button variant="outline" size="sm" disabled={!!busy} onClick={() => run("logs")}>logs</Button></div></div><pre className="terminal"><span>control-plane@syte:~$</span> {output}</pre><p className="muted">This project terminal has real, scoped commands for status, health, and logs. Arbitrary host-shell commands are intentionally unavailable.</p></section> }
function Access({ project, signOut }: { project?: Overview["project"]; signOut: () => Promise<void> }) { const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); async function rotate(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); try { const r = await fetch("/api/access", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ currentPassword, newPassword }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error || "Password change failed"); setCurrentPassword(""); setNewPassword(""); setMessage(data.message || "Workspace access password changed."); } catch (e) { setMessage(e instanceof Error ? e.message : "Password change failed"); } finally { setSaving(false); } } return <section className="page-grid"><Card><CardHeader><CardTitle>Workspace access</CardTitle><CardDescription>Users sign in with a dedicated access password; the Syte instance credential remains server-only.</CardDescription></CardHeader><CardContent className="stack"><Detail label="Workspace" value={project?.name || "Control Plane"}/><Detail label="Session" value="Authenticated"/><form className="stack" onSubmit={rotate}><label>Current password<Input type="password" minLength={12} value={currentPassword} onChange={e => setCurrentPassword(e.target.value)} required/></label><label>New password<Input type="password" minLength={12} value={newPassword} onChange={e => setNewPassword(e.target.value)} required/></label>{message && <p className="form-notice">{message}</p>}<Button type="submit" disabled={saving}>{saving && <Loader2 className="spin" size={15}/>}Change access password</Button></form><Button variant="destructive" onClick={signOut}>Sign out of workspace</Button></CardContent></Card><Card><CardHeader><CardTitle>Access boundary</CardTitle></CardHeader><CardContent><p className="muted">The workspace password can be changed here. The scoped Syte credential is never sent to the browser and cannot be viewed or changed from this panel.</p></CardContent></Card></section> }
function Feature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <Card className="feature"><CardHeader><div className="feature-icon">{icon}</div><CardTitle>{title}</CardTitle><CardDescription>{text}</CardDescription></CardHeader></Card> }
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <Card className="metric"><CardContent><p>{label}</p><strong>{value}</strong><span>{note}</span></CardContent></Card> }
function Detail({ label, value }: { label: string; value: string }) { return <div className="detail"><span>{label}</span><b>{value}</b></div> }
