from __future__ import annotations

import json
import zipfile
from pathlib import Path

import pytest

from syte.config import settings
from syte.project_intake import (
    analyze_project_source,
    apply_detected_build_plan,
    discover_environment_keys,
    extract_zip_to_project,
)
from syte.workspace import ensure_workspace


def _use_workspace_root(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    monkeypatch.setattr(settings, "workspaces_dir", tmp_path / "workspaces")


def _archive(path: Path, files: dict[str, str]) -> None:
    with zipfile.ZipFile(path, "w") as archive:
        for name, content in files.items():
            archive.writestr(name, content)


def test_zip_import_detects_next_and_suggests_environment_keys(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    _use_workspace_root(monkeypatch, tmp_path)
    archive = tmp_path / "sample.zip"
    _archive(
        archive,
        {
            "sample/package.json": json.dumps({
                "packageManager": "pnpm@9.0.0",
                "scripts": {"build": "next build", "start": "next start"},
                "dependencies": {"next": "15", "react": "19"},
            }),
            "sample/pnpm-lock.yaml": "lockfileVersion: '9.0'\n",
            "sample/app/page.tsx": "const url = process.env.NEXT_PUBLIC_API_URL;\n",
            "sample/lib/db.ts": "const value = process.env.DATABASE_URL;\n",
            "sample/.env.example": "OPTIONAL_TOKEN=\nPORT=3000\n",
        },
    )

    result = extract_zip_to_project("next-app", archive)
    analysis = analyze_project_source("next-app", source_type="zip")

    assert result["files"] == 5
    assert analysis["status"] == "ready"
    assert analysis["language"] == "node"
    assert analysis["framework"] == "nextjs"
    assert analysis["package_manager"] == "pnpm"
    assert analysis["build_pack"] == "railpack"
    assert analysis["start_command"]
    assert "FROM node:" in analysis["generated_dockerfile"]
    assert {item["key"] for item in analysis["environment_suggestions"]} == {
        "DATABASE_URL", "NEXT_PUBLIC_API_URL", "OPTIONAL_TOKEN"
    }


def test_zip_import_rejects_path_traversal(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    _use_workspace_root(monkeypatch, tmp_path)
    archive = tmp_path / "unsafe.zip"
    _archive(archive, {"../outside.txt": "nope"})

    with pytest.raises(ValueError, match="unsafe|outside"):
        extract_zip_to_project("unsafe-app", archive)

    assert not (tmp_path / "outside.txt").exists()


def test_existing_dockerfile_is_preserved_and_reported(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    _use_workspace_root(monkeypatch, tmp_path)
    app = ensure_workspace("docker-app") / "app"
    (app / "package.json").write_text(json.dumps({"dependencies": {"express": "4"}}))
    (app / "Dockerfile").write_text("FROM node:20-alpine\nCMD [\"node\", \"server.js\"]\n")
    (app / "server.js").write_text("console.log('ready')\n")

    analysis = analyze_project_source("docker-app", source_type="git")

    assert analysis["status"] == "ready"
    assert analysis["build_pack"] == "dockerfile"
    assert analysis["generated_dockerfile"] == ""
    assert analysis["dockerfile_path"] == "Dockerfile"


def test_environment_discovery_never_returns_secret_values(tmp_path: Path) -> None:
    (tmp_path / ".env.example").write_text("API_TOKEN=super-secret-value\n")
    (tmp_path / "server.py").write_text("key = os.getenv('PAYMENTS_API_KEY')\n")

    suggestions = discover_environment_keys(tmp_path)

    assert {item["key"] for item in suggestions} == {"API_TOKEN", "PAYMENTS_API_KEY"}
    assert all("super-secret-value" not in str(item) for item in suggestions)


def test_detected_plan_materializes_generated_dockerfile_only_on_apply(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    _use_workspace_root(monkeypatch, tmp_path)
    app = ensure_workspace("generated-app") / "app"
    (app / "package.json").write_text(json.dumps({
        "dependencies": {"next": "15"}, "scripts": {"build": "next build", "start": "next start"},
    }))
    (app / "app").mkdir()
    (app / "app" / "page.tsx").write_text("export default function Page(){ return null }\n")

    analysis = analyze_project_source("generated-app", source_type="zip")
    assert not (app / "Dockerfile").exists()
    applied = apply_detected_build_plan("generated-app", analysis)

    assert applied["generated_dockerfile_written"] is True
    assert (app / "Dockerfile").read_text().startswith("# Generated by Syte build packs")
