from __future__ import annotations

from pathlib import Path

from syte import deployment


def test_resolve_deploy_generates_framework_dockerfile(monkeypatch, tmp_path: Path) -> None:
    project_id = "next-app"
    app = tmp_path / "app"
    app.mkdir(parents=True)
    (app / "package.json").write_text(
        '{"dependencies":{"next":"14"},"scripts":{"build":"next build","start":"next start"}}'
    )
    (app / "pnpm-lock.yaml").write_text("lockfileVersion: '9.0'\n")
    (app / "next.config.js").write_text("module.exports = {}\n")

    monkeypatch.setattr(deployment, "ensure_workspace", lambda _project_id: tmp_path)
    monkeypatch.setattr(deployment, "find_dockerfile", lambda _project_id: None)

    info, error = deployment._resolve_deploy(
        project_id,
        None,
        project={"id": project_id, "port": 3000, "start_command": ""},
    )

    assert error is None
    assert info["deploy_type"] == "docker"
    assert info["dockerfile_path"] == "Dockerfile.syte.generated"
    generated = app / info["dockerfile_path"]
    assert generated.exists()
    contents = generated.read_text()
    assert "Generated by Syte build packs" in contents
    assert "pnpm" in contents
    assert "EXPOSE 3000" in contents


def test_resolve_deploy_reports_unsupported_source(monkeypatch, tmp_path: Path) -> None:
    project_id = "unknown-app"
    app = tmp_path / "app"
    app.mkdir(parents=True)
    (app / "README.md").write_text("No runtime manifest")

    monkeypatch.setattr(deployment, "ensure_workspace", lambda _project_id: tmp_path)
    monkeypatch.setattr(deployment, "find_dockerfile", lambda _project_id: None)

    info, error = deployment._resolve_deploy(
        project_id,
        None,
        project={"id": project_id, "port": 3000, "start_command": ""},
    )

    assert info["deploy_type"] == "docker"
    assert error is not None
    assert "No deployable framework detected" in error
    assert "Dockerfile" in error


def test_unlock_phrase_removed_from_runtime_and_gui() -> None:
    auth_source = Path("syte/auth.py").read_text()
    app_source = Path("syte/static/app.js").read_text()
    assert "Unlock the Syra web UI first." not in auth_source
    assert "Unlock Syra" not in app_source
    assert "Operator authentication required" in app_source
