"""Tests for the build pack engine — detection, generated Dockerfiles, scanning.

These replace Syte's previous hard requirement for a hand-written Dockerfile
(``syte.deployment._resolve_deploy`` refuses to deploy without one), so the
coverage here is deliberately broad: one case per supported language plus the
override and failure paths.
"""

from __future__ import annotations

import json
import shlex
from pathlib import Path

import pytest

from syte.platform.build_packs import (
    DEFAULT_PORTS,
    BuildPackError,
    build_context_from_application,
    detect_compose_file,
    detect_dockerfile,
    detect_language,
    detect_node_framework,
    detect_node_package_manager,
    detect_python_manager,
    is_static_output,
    node_install_command,
    node_start_command,
    python_start_command,
    resolve_build_plan,
    scan_context,
)
from syte.platform.types import BuildContext, BuildPack


def ctx(files: list[str], package_json: dict | None = None, **kwargs) -> BuildContext:
    return BuildContext(files=frozenset(files), package_json=package_json or {}, **kwargs)


# --------------------------------------------------------------------------- #
# Detection
# --------------------------------------------------------------------------- #

LANGUAGE_CASES: dict[str, tuple[list[str], dict, str, int]] = {
    "next-pnpm": (
        ["package.json", "pnpm-lock.yaml", "next.config.js"],
        {"dependencies": {"next": "14"}, "scripts": {"build": "next build", "start": "next start"}},
        "node", 3000,
    ),
    "express-yarn": (
        ["package.json", "yarn.lock", "server.js"],
        {"dependencies": {"express": "4"}}, "node", 3000,
    ),
    "django": (["manage.py", "requirements.txt", "proj/wsgi.py"], {}, "python", 8000),
    "fastapi-uv": (["pyproject.toml", "uv.lock", "app/main.py"], {}, "python", 8000),
    "go": (["go.mod", "go.sum", "main.go"], {}, "go", 8080),
    "rust": (["Cargo.toml", "src/main.rs"], {"cargo_name": "svc"}, "rust", 8080),
    "laravel": (["composer.json", "artisan", "public/index.php"], {}, "php", 80),
    "rails": (["Gemfile", "config/application.rb", "bin/rails"], {}, "ruby", 3000),
    "maven": (["pom.xml"], {}, "java", 8080),
    "gradle": (["build.gradle", "gradlew"], {}, "java", 8080),
    "phoenix": (["mix.exs", "config/runtime.exs"], {}, "elixir", 4000),
    "dotnet": (["Api.csproj", "Program.cs"], {}, "dotnet", 8080),
    "bun": (["bun.lockb", "index.ts"], {}, "bun", 3000),
    "deno": (["deno.json", "main.ts"], {}, "deno", 8000),
    "plain-html": (["index.html", "style.css"], {}, "static", 80),
}


@pytest.mark.parametrize("label", sorted(LANGUAGE_CASES))
def test_detect_language_and_default_port(label: str) -> None:
    files, package_json, language, port = LANGUAGE_CASES[label]
    context = ctx(files, package_json)
    assert detect_language(context) == language
    plan = resolve_build_plan(BuildPack.NIXPACKS, context)
    assert plan.exposed_port == port
    assert f"EXPOSE {port}" in plan.dockerfile


@pytest.mark.parametrize("label", sorted(LANGUAGE_CASES))
def test_generated_dockerfiles_are_well_formed(label: str) -> None:
    files, package_json, _language, _port = LANGUAGE_CASES[label]
    plan = resolve_build_plan(BuildPack.NIXPACKS, ctx(files, package_json))
    dockerfile = plan.dockerfile
    assert dockerfile.startswith("# Generated by Syte build packs")
    assert dockerfile.endswith("\n")
    assert "FROM " in dockerfile
    assert "CMD " in dockerfile


@pytest.mark.parametrize("label", sorted(LANGUAGE_CASES))
def test_generated_runtimes_listen_on_all_interfaces(label: str) -> None:
    """Binding localhost inside a container is the top cause of Bad Gateway.

    Language runtimes get an explicit ``0.0.0.0``. The nginx and Apache images
    already listen on every interface via their own config, so for those the
    invariant is that we did not narrow it — asserting a literal ``0.0.0.0``
    there would be testing for something that should not be present.
    """
    files, package_json, _language, _port = LANGUAGE_CASES[label]
    dockerfile = resolve_build_plan(BuildPack.NIXPACKS, ctx(files, package_json)).dockerfile

    if "apache2-foreground" in dockerfile:
        assert "127.0.0.1" not in dockerfile
    elif "nginx" in dockerfile:
        assert "listen 80;" in dockerfile
        assert "listen [::]:80;" in dockerfile
    else:
        assert "0.0.0.0" in dockerfile


def test_detect_language_raises_actionable_error() -> None:
    with pytest.raises(BuildPackError) as excinfo:
        detect_language(ctx(["README.md", "LICENSE"]))
    message = str(excinfo.value)
    assert "Base Directory" in message
    assert "dockerfile" in message


def test_package_manager_prefers_corepack_declaration_over_lockfile() -> None:
    # A stale package-lock.json next to a `packageManager` field is common after
    # a migration; the explicit declaration must win.
    context = ctx(["package.json", "package-lock.json"], {"packageManager": "pnpm@9.1.0"})
    assert detect_node_package_manager(context) == "pnpm"


@pytest.mark.parametrize(
    ("lockfile", "expected"),
    [
        ("pnpm-lock.yaml", "pnpm"),
        ("yarn.lock", "yarn"),
        ("bun.lockb", "bun"),
        ("package-lock.json", "npm"),
    ],
)
def test_package_manager_from_lockfile(lockfile: str, expected: str) -> None:
    assert detect_node_package_manager(ctx(["package.json", lockfile])) == expected


def test_package_manager_defaults_to_npm_without_lockfile() -> None:
    assert detect_node_package_manager(ctx(["package.json"])) == "npm"


def test_npm_ci_only_used_when_lockfile_present() -> None:
    """`npm ci` hard-fails without a lockfile, which looks like a broken pack."""
    assert node_install_command("npm", ctx(["package.json"])) == "npm install"
    assert node_install_command("npm", ctx(["package.json", "package-lock.json"])) == "npm ci"


def test_frozen_lockfile_flags_are_conditional() -> None:
    assert "--frozen-lockfile" in node_install_command("pnpm", ctx(["pnpm-lock.yaml"]))
    assert "--frozen-lockfile" not in node_install_command("pnpm", ctx(["package.json"]))


def test_detect_node_framework_prefers_meta_framework_over_react() -> None:
    framework, port = detect_node_framework(
        ctx(["package.json"], {"dependencies": {"next": "14", "react": "18"}})
    )
    assert framework == "nextjs"
    assert port == 3000


def test_node_start_command_prefers_explicit_script() -> None:
    context = ctx(["package.json"], {"scripts": {"start": "node dist/server.js"}})
    assert node_start_command("npm", context, "node") == "npm run start"


def test_node_start_command_falls_back_to_entrypoint_file() -> None:
    assert node_start_command("npm", ctx(["package.json", "server.js"]), "node") == "node server.js"
    assert (
        node_start_command("npm", ctx(["package.json"]), "sveltekit") == "node build/index.js"
    )


def test_python_start_command_detects_django_wsgi_module() -> None:
    command = python_start_command(ctx(["manage.py", "myproj/wsgi.py"]))
    assert command.startswith("gunicorn myproj.wsgi:application")
    assert "0.0.0.0" in command


def test_python_start_command_detects_asgi_app() -> None:
    assert python_start_command(ctx(["app/main.py"])).startswith("uvicorn app.main:app")


@pytest.mark.parametrize(
    ("marker", "expected"),
    [("uv.lock", "uv"), ("poetry.lock", "poetry"), ("Pipfile", "pipenv"), ("requirements.txt", "pip")],
)
def test_detect_python_manager(marker: str, expected: str) -> None:
    assert detect_python_manager(ctx([marker])) == expected


# --------------------------------------------------------------------------- #
# Static routing
# --------------------------------------------------------------------------- #


def test_spa_frameworks_auto_route_to_static_pack() -> None:
    """Coolify's docs tell you to switch manually; Syte detects it."""
    context = ctx(
        ["package.json", "index.html"],
        {"devDependencies": {"vite": "5"}, "scripts": {"build": "vite build"}},
    )
    assert is_static_output(context)
    plan = resolve_build_plan(BuildPack.NIXPACKS, context)
    assert plan.build_pack is BuildPack.STATIC
    assert plan.exposed_port == 80
    assert "nginx" in plan.dockerfile
    assert any("static build pack automatically" in note for note in plan.notes)


def test_server_rendered_framework_is_not_routed_to_static() -> None:
    context = ctx(
        ["package.json"],
        {"dependencies": {"next": "14"}, "scripts": {"build": "next build", "start": "next start"}},
    )
    assert not is_static_output(context)
    assert resolve_build_plan(BuildPack.NIXPACKS, context).build_pack is BuildPack.NIXPACKS


def test_astro_with_start_script_stays_server_rendered() -> None:
    context = ctx(
        ["package.json"],
        {"dependencies": {"astro": "4"}, "scripts": {"build": "astro build", "start": "node ./dist/server/entry.mjs"}},
    )
    assert not is_static_output(context)


def test_static_nginx_config_contains_no_single_quotes() -> None:
    """The config is emitted inside a shell single-quoted `printf` argument.

    A nested single quote would terminate the shell string early and write a
    syntactically broken nginx config — the container would then exit on start.
    """
    plan = resolve_build_plan(BuildPack.STATIC, ctx(["index.html"]))
    printf_lines = [line for line in plan.dockerfile.splitlines() if "printf" in line]
    assert printf_lines
    # shlex parsing succeeding proves the quoting is balanced.
    tokens = shlex.split(printf_lines[0])
    assert "server {" in tokens
    assert any("try_files" in token for token in tokens)


def test_static_spa_fallback_only_for_built_frontends() -> None:
    spa = resolve_build_plan(
        BuildPack.STATIC,
        ctx(["package.json", "index.html"], {"devDependencies": {"vite": "5"}, "scripts": {"build": "x"}}),
    )
    plain = resolve_build_plan(BuildPack.STATIC, ctx(["index.html"]))
    assert "/index.html;" in spa.dockerfile
    assert "=404;" in plain.dockerfile


def test_plain_static_skips_the_node_toolchain() -> None:
    plan = resolve_build_plan(BuildPack.STATIC, ctx(["index.html"]))
    assert "node:" not in plan.dockerfile


# --------------------------------------------------------------------------- #
# Non-generating build packs
# --------------------------------------------------------------------------- #


def test_dockerfile_pack_does_not_generate() -> None:
    plan = resolve_build_plan(BuildPack.DOCKERFILE, ctx([]))
    assert plan.generated is False
    assert plan.dockerfile == ""
    assert plan.dockerfile_path == "Dockerfile"


def test_dockerfile_pack_honours_explicit_location() -> None:
    context = ctx([], {"dockerfile_location": "/deploy/Dockerfile.web"})
    assert resolve_build_plan(BuildPack.DOCKERFILE, context).dockerfile_path == "deploy/Dockerfile.web"


def test_compose_pack_warns_about_rolling_updates() -> None:
    plan = resolve_build_plan(BuildPack.DOCKERCOMPOSE, ctx([]))
    assert plan.generated is False
    assert any("Rolling updates are not available" in note for note in plan.notes)


def test_dockerimage_pack_skips_build() -> None:
    plan = resolve_build_plan(BuildPack.DOCKERIMAGE, ctx([]))
    assert plan.generated is False
    assert any("no build step" in note for note in plan.notes)


def test_railpack_preserves_selected_pack() -> None:
    plan = resolve_build_plan(BuildPack.RAILPACK, ctx(["go.mod"]))
    assert plan.build_pack is BuildPack.RAILPACK
    assert plan.language == "go"


# --------------------------------------------------------------------------- #
# Operator overrides
# --------------------------------------------------------------------------- #


def test_application_row_overrides_beat_detection() -> None:
    app = {
        "ports_exposes": "9999",
        "publish_directory": "out",
        "install_command": "npm i --legacy-peer-deps",
        "build_command": "npm run export",
        "static_image": "nginx:1.27-alpine",
    }
    context = build_context_from_application(
        app,
        files=frozenset({"package.json", "index.html"}),
        package_json={"devDependencies": {"vite": "5"}, "scripts": {"build": "vite build"}},
    )
    dockerfile = resolve_build_plan(BuildPack.STATIC, context).dockerfile
    assert "npm i --legacy-peer-deps" in dockerfile
    assert "npm run export" in dockerfile
    assert "/app/out" in dockerfile
    assert "nginx:1.27-alpine" in dockerfile


def test_explicit_port_overrides_language_default() -> None:
    plan = resolve_build_plan(BuildPack.NIXPACKS, ctx(["go.mod"], port=7000))
    assert plan.exposed_port == 7000
    assert "EXPOSE 7000" in plan.dockerfile
    assert DEFAULT_PORTS["go"] != 7000


def test_unparseable_ports_exposes_falls_back_to_detection() -> None:
    context = build_context_from_application({"ports_exposes": "not-a-port"})
    assert context.port == 0


def test_build_args_are_exposed_as_arg_and_env() -> None:
    """Vite and Next only read process.env, so ARG alone is not enough."""
    plan = resolve_build_plan(
        BuildPack.NIXPACKS,
        ctx(["go.mod"], build_args=(("API_URL", "https://x"), ("BAD NAME", "y"))),
    )
    assert "ARG API_URL" in plan.dockerfile
    assert "ENV API_URL=$API_URL" in plan.dockerfile
    assert "BAD NAME" not in plan.dockerfile


# --------------------------------------------------------------------------- #
# Filesystem scanning
# --------------------------------------------------------------------------- #


def test_scan_context_skips_heavy_directories(tmp_path: Path) -> None:
    (tmp_path / "package.json").write_text(json.dumps({"dependencies": {"express": "4"}}))
    (tmp_path / "server.js").write_text("x")
    for skipped in ("node_modules", ".git", "dist", "__pycache__"):
        (tmp_path / skipped).mkdir()
        (tmp_path / skipped / "junk").write_text("x")

    files, package_json = scan_context(tmp_path)
    assert "package.json" in files
    assert "server.js" in files
    assert not any(name.startswith(("node_modules/", ".git/", "dist/")) for name in files)
    assert package_json["dependencies"] == {"express": "4"}


def test_scan_context_honours_base_directory(tmp_path: Path) -> None:
    (tmp_path / "frontend").mkdir()
    (tmp_path / "frontend" / "package.json").write_text(json.dumps({"name": "fe"}))
    (tmp_path / "backend").mkdir()
    (tmp_path / "backend" / "go.mod").write_text("module x")

    files, package_json = scan_context(tmp_path, base_directory="/frontend")
    assert files == frozenset({"package.json"})
    assert package_json["name"] == "fe"


def test_scan_context_missing_base_directory_is_empty(tmp_path: Path) -> None:
    assert scan_context(tmp_path, base_directory="/nope") == (frozenset(), {})


def test_scan_context_tolerates_malformed_package_json(tmp_path: Path) -> None:
    """Should degrade to "Node, no framework" rather than fail the deployment."""
    (tmp_path / "package.json").write_text("{not json")
    files, package_json = scan_context(tmp_path)
    assert "package.json" in files
    assert package_json == {}
    assert detect_language(BuildContext(files=files, package_json=package_json)) == "node"


def test_scan_context_extracts_cargo_crate_name(tmp_path: Path) -> None:
    (tmp_path / "Cargo.toml").write_text('[package]\nname = "cool-svc"\nversion = "0.1.0"\n')
    _files, package_json = scan_context(tmp_path)
    assert package_json["cargo_name"] == "cool-svc"
    plan = resolve_build_plan(BuildPack.NIXPACKS, ctx(["Cargo.toml"], package_json))
    assert "/app/cool-svc" in plan.dockerfile


def test_detect_dockerfile_prefers_explicit_location(tmp_path: Path) -> None:
    (tmp_path / "Dockerfile").write_text("FROM scratch")
    (tmp_path / "deploy").mkdir()
    (tmp_path / "deploy" / "Dockerfile.web").write_text("FROM alpine")

    assert detect_dockerfile(tmp_path) == tmp_path / "Dockerfile"
    assert (
        detect_dockerfile(tmp_path, location="/deploy/Dockerfile.web")
        == tmp_path / "deploy" / "Dockerfile.web"
    )
    assert detect_dockerfile(tmp_path, base_directory="/deploy") is None


def test_detect_compose_file_checks_conventional_names(tmp_path: Path) -> None:
    assert detect_compose_file(tmp_path) is None
    (tmp_path / "compose.yaml").write_text("services: {}")
    assert detect_compose_file(tmp_path) == tmp_path / "compose.yaml"
