"""Value objects and enums for the Coolify-parity platform layer.

Everything here is pure data: no I/O, no imports from the rest of ``syte``.
That keeps the enums importable from the store, the API models, the pure
renderers and the tests without any circular-import dance.

String enums are used throughout (rather than ``IntEnum`` or bare constants) so
values round-trip through SQLite TEXT columns and JSON API payloads unchanged,
and so the wire format matches Coolify's own vocabulary — an operator migrating
from Coolify sees ``build_pack: "nixpacks"`` and ``status: "cancelled-by-user"``
exactly as they expect.
"""

from __future__ import annotations

import re
import secrets
import string
import uuid as _uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum

# --------------------------------------------------------------------------- #
# Identifiers and timestamps
# --------------------------------------------------------------------------- #

# Coolify exposes every resource by a short opaque `uuid` in API paths rather
# than a numeric primary key, which keeps IDs non-enumerable. We copy that, but
# use a base32-ish alphabet so the value is also a legal DNS label (it ends up
# inside generated container names and preview subdomains).
_UUID_ALPHABET = "abcdefghijklmnopqrstuvwxyz0123456789"
UUID_LENGTH = 20

# Docker object names, DNS labels and Caddy matcher names all tolerate this set.
_SAFE_NAME_RE = re.compile(r"[^a-z0-9-]+")


def new_uuid(length: int = UUID_LENGTH) -> str:
    """Generate a URL/DNS-safe opaque resource identifier.

    Always starts with a letter: a purely numeric leading character is invalid
    in a DNS label, and these identifiers end up in autogenerated FQDNs.
    """
    first = secrets.choice(string.ascii_lowercase)
    rest = "".join(secrets.choice(_UUID_ALPHABET) for _ in range(max(0, length - 1)))
    return first + rest


def new_password(length: int = 24) -> str:
    """Generate a password safe to embed in connection URLs and compose files.

    Deliberately excludes characters that need percent-encoding in a URI
    userinfo section (``@ : / ? # [ ] %``) and characters that YAML or a shell
    would treat specially, because these values are interpolated into
    ``postgres://user:pass@host/db`` strings and into generated compose files.
    """
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def utcnow() -> str:
    """ISO-8601 UTC timestamp — matches the format used by ``syte.database``."""
    return datetime.now(UTC).isoformat()


def safe_name(value: str, *, fallback: str = "resource", limit: int = 60) -> str:
    """Normalise an operator-supplied name into a docker/DNS-safe token."""
    slug = _SAFE_NAME_RE.sub("-", (value or "").strip().lower()).strip("-")
    slug = re.sub(r"-{2,}", "-", slug)
    if not slug:
        return fallback
    if not slug[0].isalpha():
        slug = f"{fallback}-{slug}"
    return slug[:limit].strip("-") or fallback


# --------------------------------------------------------------------------- #
# Enums
# --------------------------------------------------------------------------- #


class BuildPack(str, Enum):
    """How an application's Docker image is produced.

    Mirrors Coolify's ``BuildPackTypes``. ``RAILPACK`` is Nixpacks' successor and
    is accepted as an alias so API payloads copied from Coolify keep working;
    Syte's generator treats it as an enhanced Nixpacks.
    """

    NIXPACKS = "nixpacks"
    RAILPACK = "railpack"
    STATIC = "static"
    DOCKERFILE = "dockerfile"
    DOCKERCOMPOSE = "dockercompose"
    DOCKERIMAGE = "dockerimage"

    @property
    def generates_dockerfile(self) -> bool:
        """True when Syte synthesises the Dockerfile instead of reading one."""
        return self in {BuildPack.NIXPACKS, BuildPack.RAILPACK, BuildPack.STATIC}

    @property
    def needs_git(self) -> bool:
        """``dockerimage`` deploys a prebuilt image and needs no source tree."""
        return self is not BuildPack.DOCKERIMAGE

    @property
    def supports_rolling_update(self) -> bool:
        """Compose stacks cannot be swapped atomically, so no zero-downtime.

        This is the same limitation Coolify documents: rolling updates work for
        single-container deployments only.
        """
        return self is not BuildPack.DOCKERCOMPOSE


class ResourceType(str, Enum):
    """Kinds of deployable thing an environment can hold."""

    APPLICATION = "application"
    DATABASE = "database"
    SERVICE = "service"

    @property
    def table(self) -> str:
        return {
            ResourceType.APPLICATION: "platform_applications",
            ResourceType.DATABASE: "platform_databases",
            ResourceType.SERVICE: "platform_services",
        }[self]


class DatabaseType(str, Enum):
    """The eight managed database engines Coolify provisions one-click."""

    POSTGRESQL = "postgresql"
    MYSQL = "mysql"
    MARIADB = "mariadb"
    MONGODB = "mongodb"
    REDIS = "redis"
    KEYDB = "keydb"
    DRAGONFLY = "dragonfly"
    CLICKHOUSE = "clickhouse"

    @property
    def is_key_value(self) -> bool:
        """Key-value stores have no named databases and no logical dump tool."""
        return self in {DatabaseType.REDIS, DatabaseType.KEYDB, DatabaseType.DRAGONFLY}

    @property
    def supports_backup(self) -> bool:
        """Only engines with a logical dump utility can be scheduled-backed-up.

        Matches Coolify: PostgreSQL, MySQL, MariaDB and MongoDB have dump
        tooling; the key-value stores are snapshot-based and ClickHouse needs
        its own native backup path.
        """
        return self in {
            DatabaseType.POSTGRESQL,
            DatabaseType.MYSQL,
            DatabaseType.MARIADB,
            DatabaseType.MONGODB,
        }


class DeploymentStatus(str, Enum):
    """Deployment queue states — values match Coolify's enum exactly.

    Note the hyphen in ``cancelled-by-user``; it is not a typo, it is the wire
    value Coolify uses and API consumers may match on it literally.
    """

    QUEUED = "queued"
    IN_PROGRESS = "in_progress"
    FINISHED = "finished"
    FAILED = "failed"
    CANCELLED_BY_USER = "cancelled-by-user"

    @property
    def is_terminal(self) -> bool:
        return self in {
            DeploymentStatus.FINISHED,
            DeploymentStatus.FAILED,
            DeploymentStatus.CANCELLED_BY_USER,
        }

    @property
    def is_active(self) -> bool:
        return not self.is_terminal


class ContainerStatus(str, Enum):
    """Docker container lifecycle states, as reported by ``docker inspect``."""

    CREATED = "created"
    RUNNING = "running"
    PAUSED = "paused"
    RESTARTING = "restarting"
    REMOVING = "removing"
    EXITED = "exited"
    DEAD = "dead"
    UNKNOWN = "unknown"

    @property
    def is_healthy_ish(self) -> bool:
        return self in {ContainerStatus.RUNNING, ContainerStatus.RESTARTING}


class ResourceStatus(str, Enum):
    """Aggregate status shown on a resource card in the dashboard."""

    RUNNING = "running"
    DEGRADED = "degraded"
    STOPPED = "stopped"
    EXITED = "exited"
    STARTING = "starting"
    DEPLOYING = "deploying"
    ERROR = "error"


class ServerStatus(str, Enum):
    """Reachability/usability of a managed server."""

    REACHABLE = "reachable"
    UNREACHABLE = "unreachable"
    UNUSABLE = "unusable"
    VALIDATING = "validating"
    UNKNOWN = "unknown"


class ProxyType(str, Enum):
    """Reverse proxy driving a server's ingress.

    Syte's native proxy is Caddy (``syte.certificates`` writes a Caddyfile), so
    ``CADDY`` is the default. Traefik and Nginx are modelled because Coolify
    exposes them and because a server may already be running one.
    """

    CADDY = "CADDY"
    TRAEFIK = "TRAEFIK"
    NGINX = "NGINX"
    NONE = "NONE"


class RedirectType(str, Enum):
    """www / non-www canonicalisation for an application's domains."""

    BOTH = "both"
    WWW = "www"
    NON_WWW = "non-www"


class VariableScope(str, Enum):
    """Where a shared environment variable is inherited from.

    Resolution order is team → project → environment → resource, with the
    narrowest scope winning. Same precedence as Coolify.
    """

    TEAM = "team"
    PROJECT = "project"
    ENVIRONMENT = "environment"
    RESOURCE = "resource"

    @property
    def precedence(self) -> int:
        return {
            VariableScope.TEAM: 0,
            VariableScope.PROJECT: 1,
            VariableScope.ENVIRONMENT: 2,
            VariableScope.RESOURCE: 3,
        }[self]


class GitProvider(str, Enum):
    """Supported git hosts for source cloning and inbound webhooks."""

    GITHUB = "github"
    GITLAB = "gitlab"
    GITEA = "gitea"
    BITBUCKET = "bitbucket"
    OTHER = "other"


class GitAuthMethod(str, Enum):
    """How Syte authenticates when cloning."""

    PUBLIC = "public"
    DEPLOY_KEY = "private-deploy-key"
    GITHUB_APP = "private-gh-app"
    TOKEN = "private-token"


class NotificationChannel(str, Enum):
    """Outbound notification transports."""

    EMAIL = "email"
    DISCORD = "discord"
    SLACK = "slack"
    TELEGRAM = "telegram"
    PUSHOVER = "pushover"
    WEBHOOK = "webhook"


class NotificationEvent(str, Enum):
    """Events an operator can subscribe a channel to."""

    DEPLOYMENT_STARTED = "deployment.started"
    DEPLOYMENT_SUCCESS = "deployment.success"
    DEPLOYMENT_FAILED = "deployment.failed"
    BACKUP_SUCCESS = "backup.success"
    BACKUP_FAILED = "backup.failed"
    SCHEDULED_TASK_FAILED = "scheduled_task.failed"
    SERVER_UNREACHABLE = "server.unreachable"
    SERVER_REACHABLE = "server.reachable"
    SERVER_DISK_USAGE = "server.disk_usage"
    CONTAINER_STOPPED = "container.stopped"
    DOCKER_CLEANUP = "docker.cleanup"

    @property
    def severity(self) -> str:
        """Drives colour/emoji selection in the channel payload builders."""
        if self in {
            NotificationEvent.DEPLOYMENT_FAILED,
            NotificationEvent.BACKUP_FAILED,
            NotificationEvent.SCHEDULED_TASK_FAILED,
            NotificationEvent.SERVER_UNREACHABLE,
            NotificationEvent.CONTAINER_STOPPED,
        }:
            return "error"
        if self in {NotificationEvent.SERVER_DISK_USAGE}:
            return "warning"
        return "success"


class ExecutionStatus(str, Enum):
    """Result of a scheduled task run or backup run."""

    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"


class VolumeKind(str, Enum):
    """Persistent storage flavours attachable to a resource."""

    VOLUME = "volume"
    BIND = "bind"
    FILE = "file"


class DestinationKind(str, Enum):
    """Docker destination — a network on a server, standalone or swarm."""

    STANDALONE = "standalone"
    SWARM = "swarm"


class DeploymentTrigger(str, Enum):
    """What caused a deployment to be enqueued.

    Surfaced in the deployment list so an operator can tell an automatic
    push-triggered build from one they clicked.
    """

    MANUAL = "manual"
    WEBHOOK = "webhook"
    API = "api"
    SCHEDULE = "schedule"
    ROLLBACK = "rollback"
    RESTART = "restart"


# --------------------------------------------------------------------------- #
# Configuration value objects
# --------------------------------------------------------------------------- #


@dataclass(frozen=True, slots=True)
class HealthCheckConfig:
    """Container healthcheck definition.

    Fields mirror Coolify's ``health_check_*`` application columns. A container
    healthcheck is what makes rolling (zero-downtime) updates possible: the new
    container must report healthy before the old one is removed.
    """

    enabled: bool = True
    path: str = "/"
    port: int | None = None
    host: str = "127.0.0.1"
    method: str = "GET"
    scheme: str = "http"
    return_code: int = 200
    response_text: str | None = None
    interval: int = 30
    timeout: int = 30
    retries: int = 3
    start_period: int = 30
    command: str | None = None

    def probe_command(self, *, container_port: int | None = None) -> str:
        """Shell command used as the container's ``HEALTHCHECK`` test.

        A custom ``command`` always wins. Otherwise we curl the configured
        endpoint. ``--noproxy '*'`` prevents a proxy env var leaking in from the
        image and making the probe check the wrong host, and ``-f`` turns a
        non-2xx response into a non-zero exit so docker marks it unhealthy.
        """
        if self.command:
            return self.command
        port = self.port or container_port or 80
        url = f"{self.scheme}://{self.host}:{port}{self.path or '/'}"
        method = (self.method or "GET").upper()
        parts = [
            "curl",
            "-f",
            "-s",
            "-S",
            "--noproxy",
            "'*'",
            "-o",
            "/dev/null",
            "-X",
            method,
            "--max-time",
            str(max(1, self.timeout)),
            f"'{url}'",
        ]
        return " ".join(parts)

    def docker_args(self, *, container_port: int | None = None) -> list[str]:
        """``docker run`` flags implementing this healthcheck."""
        if not self.enabled:
            return ["--no-healthcheck"]
        return [
            "--health-cmd",
            self.probe_command(container_port=container_port),
            "--health-interval",
            f"{max(1, self.interval)}s",
            "--health-timeout",
            f"{max(1, self.timeout)}s",
            "--health-retries",
            str(max(1, self.retries)),
            "--health-start-period",
            f"{max(0, self.start_period)}s",
        ]

    def compose_healthcheck(self, *, container_port: int | None = None) -> dict[str, object]:
        """Equivalent block for a compose service definition."""
        if not self.enabled:
            return {"disable": True}
        return {
            "test": ["CMD-SHELL", self.probe_command(container_port=container_port)],
            "interval": f"{max(1, self.interval)}s",
            "timeout": f"{max(1, self.timeout)}s",
            "retries": max(1, self.retries),
            "start_period": f"{max(0, self.start_period)}s",
        }

    @classmethod
    def from_row(cls, row: dict[str, object]) -> HealthCheckConfig:
        """Build from a ``platform_applications`` row (or any dict subset)."""

        def _int(key: str, default: int) -> int:
            raw = row.get(key)
            try:
                return int(raw)  # type: ignore[arg-type]
            except (TypeError, ValueError):
                return default

        port_raw = row.get("health_check_port")
        try:
            port = int(port_raw) if port_raw not in (None, "", 0) else None
        except (TypeError, ValueError):
            port = None

        return cls(
            enabled=bool(row.get("health_check_enabled", True)),
            path=str(row.get("health_check_path") or "/"),
            port=port,
            host=str(row.get("health_check_host") or "127.0.0.1"),
            method=str(row.get("health_check_method") or "GET"),
            scheme=str(row.get("health_check_scheme") or "http"),
            return_code=_int("health_check_return_code", 200),
            response_text=(str(row["health_check_response_text"])
                           if row.get("health_check_response_text") else None),
            interval=_int("health_check_interval", 30),
            timeout=_int("health_check_timeout", 30),
            retries=_int("health_check_retries", 3),
            start_period=_int("health_check_start_period", 30),
            command=(str(row["health_check_command"])
                     if row.get("health_check_command") else None),
        )


# Values meaning "no limit" — accepted for every limits_* field so an operator
# can explicitly opt out of a cap. Mirrors syte.docker_deploy._UNLIMITED.
UNLIMITED_VALUES = frozenset({"", "0", "0b", "none", "unlimited", "off", "-1"})


@dataclass(frozen=True, slots=True)
class ResourceLimits:
    """CPU/memory caps applied to a container.

    Defaults are empty (inherit the daemon default) rather than the aggressive
    1g/1cpu that ``syte.docker_deploy`` hardcodes, because a managed database or
    a compose service legitimately needs more than an app container. The caller
    decides; ``syte.platform.service`` fills in server-level defaults.
    """

    memory: str = ""
    memory_swap: str = ""
    memory_swappiness: int | None = None
    memory_reservation: str = ""
    cpus: str = ""
    cpuset: str = ""
    cpu_shares: int | None = None
    pids_limit: int | None = None

    @staticmethod
    def _is_set(value: str) -> bool:
        return str(value or "").strip().lower() not in UNLIMITED_VALUES

    def docker_args(self) -> list[str]:
        """``docker run`` flags for the configured caps only."""
        args: list[str] = []
        if self._is_set(self.memory):
            args += ["--memory", self.memory.strip()]
        if self._is_set(self.memory_swap):
            args += ["--memory-swap", self.memory_swap.strip()]
        if self.memory_swappiness is not None and 0 <= self.memory_swappiness <= 100:
            args += ["--memory-swappiness", str(self.memory_swappiness)]
        if self._is_set(self.memory_reservation):
            args += ["--memory-reservation", self.memory_reservation.strip()]
        if self._is_set(self.cpus):
            args += ["--cpus", self.cpus.strip()]
        if self._is_set(self.cpuset):
            args += ["--cpuset-cpus", self.cpuset.strip()]
        if self.cpu_shares and self.cpu_shares > 0:
            args += ["--cpu-shares", str(self.cpu_shares)]
        if self.pids_limit and self.pids_limit > 0:
            args += ["--pids-limit", str(self.pids_limit)]
        return args

    @classmethod
    def from_row(cls, row: dict[str, object]) -> ResourceLimits:
        def _opt_int(key: str) -> int | None:
            raw = row.get(key)
            if raw in (None, ""):
                return None
            try:
                return int(raw)  # type: ignore[arg-type]
            except (TypeError, ValueError):
                return None

        return cls(
            memory=str(row.get("limits_memory") or ""),
            memory_swap=str(row.get("limits_memory_swap") or ""),
            memory_swappiness=_opt_int("limits_memory_swappiness"),
            memory_reservation=str(row.get("limits_memory_reservation") or ""),
            cpus=str(row.get("limits_cpus") or ""),
            cpuset=str(row.get("limits_cpuset") or ""),
            cpu_shares=_opt_int("limits_cpu_shares"),
            pids_limit=_opt_int("limits_pids"),
        )


@dataclass(frozen=True, slots=True)
class DomainRoute:
    """One parsed entry from a resource's FQDN list.

    Coolify's ``fqdn`` column is a comma-separated list of URLs where each entry
    may carry a path and an explicit upstream port, e.g.::

        https://app.example.com,https://api.example.com/v1:8080

    Splitting that into structured routes is what lets the proxy layer emit
    path-scoped ``handle`` blocks instead of one dumb host block.
    """

    hostname: str
    port: int
    path: str = "/"
    scheme: str = "https"

    @property
    def is_root_path(self) -> bool:
        return self.path in ("", "/")

    @property
    def url(self) -> str:
        suffix = "" if self.is_root_path else self.path
        return f"{self.scheme}://{self.hostname}{suffix}"


@dataclass(frozen=True, slots=True)
class PortMapping:
    """A ``host:container`` port publication."""

    host_port: int
    container_port: int
    protocol: str = "tcp"

    def docker_arg(self) -> str:
        suffix = "" if self.protocol == "tcp" else f"/{self.protocol}"
        return f"{self.host_port}:{self.container_port}{suffix}"


@dataclass(frozen=True, slots=True)
class VolumeMount:
    """Persistent storage attached to a container."""

    kind: VolumeKind
    name: str
    mount_path: str
    host_path: str = ""
    content: str = ""
    is_directory: bool = False

    def docker_arg(self) -> str:
        """Source spec for ``-v``.

        Named volumes survive container recreation, which is the whole point of
        preferring them over bind mounts for database data.
        """
        if self.kind is VolumeKind.VOLUME:
            return f"{self.name}:{self.mount_path}"
        return f"{self.host_path or self.name}:{self.mount_path}"


@dataclass(frozen=True, slots=True)
class BasicAuthConfig:
    """HTTP basic auth enforced at the proxy, ahead of the container."""

    enabled: bool = False
    username: str = ""
    password_hash: str = ""

    @property
    def is_usable(self) -> bool:
        return bool(self.enabled and self.username and self.password_hash)


@dataclass(frozen=True, slots=True)
class BuildContext:
    """Everything a build pack needs to synthesise a Dockerfile.

    ``files`` is the set of repository-root-relative paths that exist in the
    source tree. Passing a plain set (rather than a ``Path``) is what keeps the
    detection logic pure and testable without touching a filesystem.
    """

    files: frozenset[str] = frozenset()
    package_json: dict[str, object] = field(default_factory=dict)
    base_directory: str = "/"
    publish_directory: str = ""
    install_command: str = ""
    build_command: str = ""
    start_command: str = ""
    static_image: str = "nginx:alpine"
    node_version: str = ""
    python_version: str = ""
    build_args: tuple[tuple[str, str], ...] = ()
    # 0 means "not specified" so build packs fall back to their language
    # default. A real default here would silently override every generator.
    port: int = 0

    def has(self, *candidates: str) -> bool:
        return any(candidate in self.files for candidate in candidates)

    def has_any_suffix(self, suffix: str) -> bool:
        return any(name.endswith(suffix) for name in self.files)


@dataclass(frozen=True, slots=True)
class BuildPlan:
    """Result of running a build pack against a :class:`BuildContext`."""

    build_pack: BuildPack
    language: str
    dockerfile: str
    context_directory: str = "."
    dockerfile_path: str = "Dockerfile"
    exposed_port: int = 3000
    install_command: str = ""
    build_command: str = ""
    start_command: str = ""
    notes: tuple[str, ...] = ()
    generated: bool = True

    def as_dict(self) -> dict[str, object]:
        return {
            "build_pack": self.build_pack.value,
            "language": self.language,
            "context_directory": self.context_directory,
            "dockerfile_path": self.dockerfile_path,
            "exposed_port": self.exposed_port,
            "install_command": self.install_command,
            "build_command": self.build_command,
            "start_command": self.start_command,
            "notes": list(self.notes),
            "generated": self.generated,
        }


@dataclass(frozen=True, slots=True)
class DeploymentRequest:
    """Input to :func:`syte.platform.deployments.enqueue`.

    Kept as a value object rather than a pile of keyword arguments because the
    same request shape arrives from four places (dashboard button, ``/api/v1``,
    an inbound git webhook, and the rollback action) and each needs to record a
    different ``trigger``.
    """

    resource_uuid: str
    resource_type: ResourceType = ResourceType.APPLICATION
    trigger: DeploymentTrigger = DeploymentTrigger.MANUAL
    force_rebuild: bool = False
    restart_only: bool = False
    commit: str = "HEAD"
    commit_message: str = ""
    pull_request_id: int = 0
    rollback_image_tag: str = ""
    requested_by: str = ""

    @property
    def is_rollback(self) -> bool:
        return bool(self.rollback_image_tag)

    @property
    def is_preview(self) -> bool:
        return self.pull_request_id > 0


@dataclass(frozen=True, slots=True)
class DeploymentStep:
    """One line item in the deployment plan, surfaced in the log viewer."""

    name: str
    detail: str = ""
    skipped: bool = False


@dataclass(frozen=True, slots=True)
class DeploymentPlan:
    """The ordered work a deployment will perform.

    Computing this up front (before any side effect) means the dashboard can
    show the operator what is about to happen, the log stream gets stable step
    names, and the whole thing is unit-testable without Docker.
    """

    resource_uuid: str
    resource_type: ResourceType
    build_pack: BuildPack
    image: str
    image_tag: str
    container_name: str
    steps: tuple[DeploymentStep, ...] = ()
    rolling_update: bool = False
    restart_only: bool = False
    config_changed: bool = True

    @property
    def image_ref(self) -> str:
        return f"{self.image}:{self.image_tag}"

    def as_dict(self) -> dict[str, object]:
        return {
            "resource_uuid": self.resource_uuid,
            "resource_type": self.resource_type.value,
            "build_pack": self.build_pack.value,
            "image": self.image,
            "image_tag": self.image_tag,
            "image_ref": self.image_ref,
            "container_name": self.container_name,
            "rolling_update": self.rolling_update,
            "restart_only": self.restart_only,
            "config_changed": self.config_changed,
            "steps": [
                {"name": step.name, "detail": step.detail, "skipped": step.skipped}
                for step in self.steps
            ],
        }


@dataclass(frozen=True, slots=True)
class EnvVar:
    """A resolved environment variable ready to hand to Docker.

    ``is_build_time`` / ``is_runtime`` are independent flags, not a two-value
    enum: a variable such as ``NEXT_PUBLIC_API_URL`` is legitimately needed at
    both build and run time, and Coolify models it the same way.
    """

    key: str
    value: str
    is_build_time: bool = False
    is_runtime: bool = True
    is_literal: bool = False
    is_secret: bool = False
    scope: VariableScope = VariableScope.RESOURCE

    def masked(self) -> str:
        """Value safe to render in a log line or an API response."""
        if not self.is_secret:
            return self.value
        if len(self.value) <= 4:
            return "****"
        return f"{self.value[:2]}{'*' * 8}{self.value[-2:]}"


@dataclass(frozen=True, slots=True)
class ServerTarget:
    """Where a deployment runs.

    A ``ServerTarget`` with ``is_local`` true executes commands directly; a
    remote one tunnels them over SSH. Every effectful helper in
    ``docker_engine`` takes one of these so the same code path handles both,
    which is what unblocks multi-server support.
    """

    uuid: str = "localhost"
    name: str = "localhost"
    ip: str = "127.0.0.1"
    user: str = "root"
    port: int = 22
    private_key_path: str = ""
    is_local: bool = True
    docker_network: str = "syte"
    proxy_type: ProxyType = ProxyType.CADDY
    concurrent_builds: int = 2
    connection_timeout: int = 30

    def ssh_prefix(self) -> list[str]:
        """argv prefix that runs a command on this server.

        Empty for the local server. For a remote one we disable strict host key
        checking against a throwaway known-hosts file: Syte manages the server
        inventory itself, and a prompt here would hang the deployment worker
        forever with no way for the operator to answer it.
        """
        if self.is_local:
            return []
        argv = [
            "ssh",
            "-o", "BatchMode=yes",
            "-o", "StrictHostKeyChecking=accept-new",
            "-o", f"ConnectTimeout={max(1, self.connection_timeout)}",
            "-p", str(self.port),
        ]
        if self.private_key_path:
            argv += ["-i", self.private_key_path]
        argv.append(f"{self.user}@{self.ip}")
        return argv


@dataclass(frozen=True, slots=True)
class MagicVariable:
    """A Coolify "magic" compose variable and the value Syte generated for it.

    Service templates declare placeholders such as ``SERVICE_PASSWORD_MYSQL``
    or ``SERVICE_FQDN_GHOST``; on first deploy the platform materialises a
    concrete value and persists it so subsequent deploys are stable.
    """

    key: str
    value: str
    kind: str  # fqdn | url | password | password64 | user | base64 | realbase64
    target: str = ""
    generated: bool = True


@dataclass(frozen=True, slots=True)
class ServiceTemplate:
    """A one-click service definition from the catalog."""

    key: str
    name: str
    description: str
    category: str
    compose: str
    tags: tuple[str, ...] = ()
    documentation: str = ""
    logo: str = ""
    minimum_memory_mb: int = 256

    def as_dict(self) -> dict[str, object]:
        return {
            "key": self.key,
            "name": self.name,
            "description": self.description,
            "category": self.category,
            "tags": list(self.tags),
            "documentation": self.documentation,
            "logo": self.logo,
            "minimum_memory_mb": self.minimum_memory_mb,
        }


@dataclass(frozen=True, slots=True)
class DatabaseEngine:
    """Static definition of a managed database engine."""

    database_type: DatabaseType
    name: str
    default_image: str
    default_port: int
    data_path: str
    scheme: str
    supported_versions: tuple[str, ...] = ()
    default_username: str = ""
    default_database: str = ""
    dump_binary: str = ""
    restore_binary: str = ""
    client_binary: str = ""
    minimum_memory_mb: int = 256

    def as_dict(self) -> dict[str, object]:
        return {
            "type": self.database_type.value,
            "name": self.name,
            "default_image": self.default_image,
            "default_port": self.default_port,
            "scheme": self.scheme,
            "supported_versions": list(self.supported_versions),
            "supports_backup": self.database_type.supports_backup,
            "is_key_value": self.database_type.is_key_value,
            "minimum_memory_mb": self.minimum_memory_mb,
        }


# --------------------------------------------------------------------------- #
# Docker label keys
# --------------------------------------------------------------------------- #

# Every container Syte creates carries these labels. They are the only reliable
# way to reconcile "what should be running" against "what is running" after a
# restart, and to attribute a stray container to a resource during cleanup.
LABEL_MANAGED = "syte.managed"
LABEL_RESOURCE_UUID = "syte.resource.uuid"
LABEL_RESOURCE_TYPE = "syte.resource.type"
LABEL_RESOURCE_NAME = "syte.resource.name"
LABEL_ENVIRONMENT_UUID = "syte.environment.uuid"
LABEL_PROJECT_UUID = "syte.project.uuid"
LABEL_SERVER_UUID = "syte.server.uuid"
LABEL_DEPLOYMENT_UUID = "syte.deployment.uuid"
LABEL_PULL_REQUEST = "syte.pull_request"
LABEL_CONFIG_HASH = "syte.config.hash"
LABEL_IMAGE_TAG = "syte.image.tag"

# Applied to the temporary container created during a rolling update so a
# crashed deployment leaves an obviously-disposable object behind.
LABEL_ROLLING = "syte.rolling"

MANAGED_LABEL_VALUE = "true"


def managed_labels(
    *,
    resource_uuid: str,
    resource_type: ResourceType,
    resource_name: str = "",
    environment_uuid: str = "",
    project_uuid: str = "",
    server_uuid: str = "",
    deployment_uuid: str = "",
    pull_request_id: int = 0,
    config_hash: str = "",
    image_tag: str = "",
) -> dict[str, str]:
    """Build the label map for a managed container. Empty values are dropped."""
    labels = {
        LABEL_MANAGED: MANAGED_LABEL_VALUE,
        LABEL_RESOURCE_UUID: resource_uuid,
        LABEL_RESOURCE_TYPE: resource_type.value,
        LABEL_RESOURCE_NAME: resource_name,
        LABEL_ENVIRONMENT_UUID: environment_uuid,
        LABEL_PROJECT_UUID: project_uuid,
        LABEL_SERVER_UUID: server_uuid,
        LABEL_DEPLOYMENT_UUID: deployment_uuid,
        LABEL_CONFIG_HASH: config_hash,
        LABEL_IMAGE_TAG: image_tag,
    }
    if pull_request_id:
        labels[LABEL_PULL_REQUEST] = str(pull_request_id)
    return {key: value for key, value in labels.items() if value}


# --------------------------------------------------------------------------- #
# Naming helpers
# --------------------------------------------------------------------------- #

# Docker object name prefixes. The uuid suffix guarantees uniqueness even when
# two projects contain resources with the same human name.
IMAGE_PREFIX = "syte"
CONTAINER_PREFIX = "syte"


def image_name(resource_uuid: str, name: str = "") -> str:
    """Local image repository for a resource (tag is applied separately)."""
    slug = safe_name(name, fallback="app", limit=40) if name else "app"
    return f"{IMAGE_PREFIX}/{slug}-{safe_name(resource_uuid, fallback='res', limit=24)}"


def container_name(resource_uuid: str, name: str = "", *, suffix: str = "") -> str:
    """Deterministic container name for a resource.

    Deterministic (rather than random per deployment) so ``docker logs`` and
    ``docker exec`` keep working across deployments, and so the supervisor can
    find the container after a Syte restart without consulting the database.
    """
    slug = safe_name(name, fallback="app", limit=40) if name else "app"
    base = f"{CONTAINER_PREFIX}-{slug}-{safe_name(resource_uuid, fallback='res', limit=24)}"
    return f"{base}-{safe_name(suffix, fallback='x', limit=12)}" if suffix else base


def volume_name(resource_uuid: str, label: str) -> str:
    return f"{IMAGE_PREFIX}-{safe_name(resource_uuid, fallback='res', limit=24)}-{safe_name(label, fallback='data', limit=24)}"


def network_name(project_uuid: str) -> str:
    """Per-project docker network so resources in a project can talk by name."""
    return f"{IMAGE_PREFIX}-{safe_name(project_uuid, fallback='net', limit=32)}"


def deployment_uuid() -> str:
    """Deployment identifiers are longer-lived and appear in URLs."""
    return _uuid.uuid4().hex


__all__ = [
    "CONTAINER_PREFIX",
    "IMAGE_PREFIX",
    "LABEL_CONFIG_HASH",
    "LABEL_DEPLOYMENT_UUID",
    "LABEL_ENVIRONMENT_UUID",
    "LABEL_IMAGE_TAG",
    "LABEL_MANAGED",
    "LABEL_PROJECT_UUID",
    "LABEL_PULL_REQUEST",
    "LABEL_RESOURCE_NAME",
    "LABEL_RESOURCE_TYPE",
    "LABEL_RESOURCE_UUID",
    "LABEL_ROLLING",
    "LABEL_SERVER_UUID",
    "MANAGED_LABEL_VALUE",
    "UNLIMITED_VALUES",
    "UUID_LENGTH",
    "BasicAuthConfig",
    "BuildContext",
    "BuildPack",
    "BuildPlan",
    "ContainerStatus",
    "DatabaseEngine",
    "DatabaseType",
    "DeploymentPlan",
    "DeploymentRequest",
    "DeploymentStatus",
    "DeploymentStep",
    "DeploymentTrigger",
    "DestinationKind",
    "DomainRoute",
    "EnvVar",
    "ExecutionStatus",
    "GitAuthMethod",
    "GitProvider",
    "HealthCheckConfig",
    "MagicVariable",
    "NotificationChannel",
    "NotificationEvent",
    "PortMapping",
    "ProxyType",
    "RedirectType",
    "ResourceLimits",
    "ResourceStatus",
    "ResourceType",
    "ServerStatus",
    "ServerTarget",
    "ServiceTemplate",
    "VariableScope",
    "VolumeKind",
    "VolumeMount",
    "container_name",
    "deployment_uuid",
    "image_name",
    "managed_labels",
    "network_name",
    "new_password",
    "new_uuid",
    "safe_name",
    "utcnow",
    "volume_name",
]
